### ISSUE TITLE
deltav atmos heat transfer is broken on debug

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#1021]
## Description
on debug builds at least, heat isnt transferring to adjacent tiles

i am on a 20C tile with a 10kC tile to the left of it
![14:13:00](https://github.com/DeltaV-Station/Delta-v/assets/39013340/d3f97e6f-fe3c-409c-80c1-fdbbafdd52ca)

havent checked release or upstream yet

**Comment by DangerRevolution** [comment]
atmos bug 2.0 :(

**Comment by IamVelcroboy** [comment]
Probably investigate this if you're going to test on an upstream build as well. <https://github.com/space-wizards/space-station-14/pull/22521>

**Comment by deltanedas** [comment]
ok this happens upstream too

**Comment by stellar-novas** [comment]
Does this happen on release?

**Comment by deltanedas** [comment]
checking now but it happens upstream so #26513
