### ISSUE TITLE
urgent: magical lamp needs to be disabled from expedition pool

### ISSUE THREAD

**Issue by DangerRevolution** [DeltaV-Station/Delta-v#1033]
## Description

in the loot pool for expeditions; spawns a holoparasite on use, which are still invincible

**Comment by DangerRevolution** [comment]
https://github.com/DeltaV-Station/Delta-v/blob/f6714a5927587430b9a7da0e507029825966e159/Resources/Maps/Dungeon/snowy_labs.yml#L10734

line 10734; it's in a dungeon

**Comment by deltanedas** [comment]
what the fuck
