### ISSUE TITLE
Change Survival Weights

### ISSUE THREAD

**Issue by rosieposieeee** [DeltaV-Station/Delta-v#1048]
## Description

See #1047.

Its called 'Survival', not 'Extended' or 'Sandbox', yet there are frequently extremely boring rounds where nothing challenges the station for the full 2 hours and then we all just go home and hope the next round is a different mode. There ARE, sometimes, fun survival rounds... when the dice rolls in favor of conflict. What it should *really* be called is 'The Self-Antag Honeypot', because I'm sure the admins always have fun.

- 4 events - the mouse/roach spawns - do literally nothing that can be interesting in any way. There is literally a duplicate mouse event that I would straight up categorize as being a bug that needs to be fixed. Remove all of them or consolidate them into one event and make sure it only happens once per shift or once every hour, which is a thing the StationEvent component can do! Getting like five mouse rolls in a row is the most disappointing shift of a lifetime.
- Paracusia is a trait you can already take. The event that sort of vaguely gives it to everyone just gets peoples hopes up when they hear fun things, and also doesn't really lead to conflict *or* very much interesting rp, just a mild annoyance. Remove it.
- Ninjas are at an unreasonably low-spawn rate despite being the most interesting antagonist and the one of the few significantly disruptive ones with goals that aren't exclusively murderboning. I'm not even asking to increase it to WD levels here, just more than it is.
- Revenant is like the most common thing to be spawned despite being the least interesting since they got nerfed to hell. They're harder to rp with than fucking dragons. They were left at a WD spawnrate when everything else got decreased, so they should be too, and severely.
- Speaking of dragons, they also basically never spawn, so that should be increased. Again, not to WD amounts, but I would like to *ever* see one on its own, which is LESS of a threat than one a ninja spawned.
- Xeno vent event got far too nerfed. 4 was too much, 1 is too little, there is an easy middleground there around 2. (Note that slimes and spiders are at 5 and I don't feel like they're _that_ much less dangerous than Xenos.)

I can, and have, already made a PR to fix these things and will do so again as soon as we can come to any kind of consensus.

**Comment by FoxFox1701** [comment]
Im fine with increasing the ninja spawns but if we're doing that we shouldnt increase the dragon spawns, as more ninjas means more dragons. And until we fix the whole "Dragons can round-remove dozens of people for free" issue, I wouldnt want even more dragons as all they do now is cause frustration.

Everything else seems fine, except maybe leave the mass paracusia just make it extra rare

**Comment by Adrian16199** [comment]
I would personally like to see some stuff become a separate timer when it comes to when they happen.
Yes I agree that the fact that instead of somethin interestin, a mouse/roach spawns, I feel like those 2 specificly should be a separate thing, separate timer, they can happen to feed the crew or steal their food, despite the fact that a second ago slimes spawned.
Thats my 2 pennies.

**Comment by rosieposieeee** [comment]
> And until we fix the whole "Dragons can round-remove dozens of people for free" issue, I wouldnt want even more dragons as all they do now is cause frustration.

fair enough, but i believe upstream has noticed the bug thanks to the recent lilten video and theres a pr open to fix it. ive certainly never minded the dragon butchering issue, because i always play a carp as soon as i get eaten.

> I feel like those 2 specificly should be a separate thing, separate timer

there is _already_ a separate thing that randomly spawns mice on a timer. i could just modify that to include cockroaches occasionally

**Comment by Axionyxx** [comment]
> 4 events - the mouse/roach spawns - do literally nothing that can be interesting in any way. There is literally a duplicate mouse event that I would straight up categorize as being a bug that needs to be fixed. Remove all of them or consolidate them into one event and make sure it only happens once per shift or once every hour, which is a thing the StationEvent component can do! Getting like five mouse rolls in a row is the most disappointing shift of a lifetime.

These are to dilute the pool, and without them you'd make the round significantly worse. RampingStationEventScheduler will attempt to run an event 4 to 12 minutes after the round starts, and every 4-12 minutes after that. The time between events decreases with every run. Removing all "boring" events will just result in a constant barage of antags and gas leaks

**Comment by rosieposieeee** [comment]
> a constant barage

that is the plan! :)

survival, as a gamemode, really shines when shit hits the fan and the crew works together to overcome conflict and has something to actually talk about. this _can't happen_ when survival is toothless like it is now in the majority of rounds.

**Comment by Axionyxx** [comment]
> > a constant barage
> 
> that is the plan! :)
> 
> survival, as a gamemode, really shines when shit hits the fan and the crew works together to overcome conflict and has something to actually talk about. this _can't happen_ when survival is toothless like it is now in the majority of rounds.

Survival, as a gamemode, is a half assed implementation(also said by the person that wrote it) that wasn't production ready. With the upcoming feature freeze and push for release it'll likely see some big improvements in how events get picked

**Comment by rosieposieeee** [comment]
> Survival, as a gamemode, is a half assed implementation(also said by the person that wrote it) that wasn't production ready. With the upcoming feature freeze and push for release it'll likely see some big improvements in how events get picked

thats fair, but i could make it a bit better right now!

**Comment by Tryded** [comment]
Can we like, just increase the chance of other gamemodes like traitor because survival is shitterfest and boring.

**Comment by AitorLogedo** [comment]
survival rn is not enought survival and just selfantag gamemode, either reducing survival rate or increase weight of events that actually do feel like survival will work. also a lot of events in survival are removed because "lol lrp" which wasent even consulted with the community as we now have to do

**Comment by deltanedas** [comment]
survival is unusable imo sometimes a 2h round is extended and nothing happens other times theres 5 minor antags and 20 slime events
