### ISSUE TITLE
Logistics Officer's cloak isn't considered a thief steal target

### ISSUE THREAD

**Issue by Tryded** [DeltaV-Station/Delta-v#1091]
## Description

LO's cloak isn't considered a head cloak in thief objective
**Reproduction**

>be thief
>roll "Steal the head's cloak"
>realize that LO's cloak doesn't count
**Screenshots**

**Additional context**

It's probably just a YAML change.

**Comment by blueDev2** [comment]
Is this an active issue? The yaml at Resources\Prototypes\Entities\Clothing\Neck\cloaks.yml seems to indicate that the LO's cloak is a head cloak target.
The Yaml at Resources\Prototypes\DeltaV\Entities\Clothing\Neck\cloaks.yml, Mysta's cloak might not count though

**Comment by blueDev2** [comment]
Nevermind about the Mysta, their cloak is in both YAMLs for some reason

**Comment by ghost** [comment]
Issue has been fixed; closing.
