### ISSUE TITLE
Some weapons don't show properly when worn in the suit slot

### ISSUE THREAD

**Issue by MilonPL** [DeltaV-Station/Delta-v#1105]
## Description
Some weapons do not show on character's back if worn in the suit slot instead of the backpack slot. I've noticed this issue with Kammerers and Vulcans, it might affect other weapons, although I haven't seen it happen with Drozds or Lecters. 

**Reproduction**
>Load in
>Put a Kammerer/Vulcan in your suit slot
>Expect it to show
>Be disappointed

**Screenshots**
![EEpid5CxT5](https://github.com/DeltaV-Station/Delta-v/assets/96891493/0e89c474-bb39-4920-b847-5783271fe8c4)
![wKXV9GY2RV](https://github.com/DeltaV-Station/Delta-v/assets/96891493/52b8c3bc-88ee-4908-9c55-9785adf47e1c)
![bVp0ZXDdnq](https://github.com/DeltaV-Station/Delta-v/assets/96891493/e4965f23-2b2c-4199-ac57-4c826e266f88)
![H7IB5y8stA](https://github.com/DeltaV-Station/Delta-v/assets/96891493/2627817b-bb52-4c3e-a389-cd1dee459971)

**Additional context**
The Kammerer shows up perfectly fine upstream, regardless if it's worn in the suit or backpack slot.

**Comment by rosieposieeee** [comment]
will be fixed by #1092
