### ISSUE TITLE
Edge evac doesn't dock at primary evac

### ISSUE THREAD

**Issue by Colin-Tel** [DeltaV-Station/Delta-v#1135]
## Description

Upon shuttle arrival on Edge station, the evac never targets the primary evac location on the west side of the station. It always resorts to docking at secondary evac on the east side.

**Reproduction**

Start a game with Edge station
`callshuttle 0:05`
it docks on the east side

**Screenshots**

N/A

**Additional context**

Gonna try moving the primary evac's docks up one tile, as the dimensions of the evac shuttle have not changed.

**Comment by Colin-Tel** [comment]
After investigation, we apparently lost `emergency_box.yml` for whatever reason and I'll bring it back to fix this.

**Comment by IamVelcroboy** [comment]
Also we have a DV version already, it's the NTES_Box. It already has the alterations we make to upstream shuttles. It just needs to be centered.

**Comment by Colin-Tel** [comment]
> After investigation, we apparently lost `emergency_box.yml` for whatever reason and I'll bring it back to fix this.

Correction, we have `Maps/Shuttles/DeltaV/NTES_Box` and we're seeing what needs to be done to it to resolve.
