### ISSUE TITLE
Vulp vision gets lost when vulp in PVS gets gibbed/removed (same for harpies)

### ISSUE THREAD

**Issue by pissdemon** [DeltaV-Station/Delta-v#1148]
## Description
If you are a vulp using the species vision, and someone in your PVS gets gibbed/destroyed, you lose your species vision until you toggle the setting for it in your settings.

The same goes for harpies if you swap out every "vulp" with "harpy" in the last paragraph.

**Reproduction** (also works for harpie-on-harpie violence)
1. Be vulp with vulp vision turned on in settings
2. Gib an Urist McVulp or some other vulp (or meatspike them, or...)
3. You lose your vulp vision

**Additional context**
The reason for this is that Client.DogVisionSystem/Client.UltraVisionSystem, when the DogVisionComponent/UltraVisionComponent get destroyed, remove their respective vision overlays from the overlay system. That cures your colorblindness. 

Not sure how to fix this cleanly, I'll try to figure it out with #1101 since that needs an overlay too

**Comment by Axionyxx** [comment]
Does this also affect the blind trait?

**Comment by pissdemon** [comment]
It doesn't because it uses a more sensible approach (see Client.BlurryVisionSystem). I'll use that for the synth stuff and make a PR later to fix vulp/harpie vision. Thanks for pointing it out.

**Comment by pissdemon** [comment]
Also just found out why vulp vision makes construction ghosts look fucked up but I'll fix that in the same PR
