### ISSUE TITLE
Beer and wine cannot be reinserted into booze dispenser

### ISSUE THREAD

**Issue by pissdemon** [DeltaV-Station/Delta-v#1149]
## Description
Self explanatory.

**Reproduction**
Get a booze dispenser, eject the wine/XL beer bottle in it, and find that you can't reinsert it.

**Additional context**
Tag inheritance issue. Booze dispenser wants DrinkBottle tagged items, but wine and the XL beer bottle override their tags and don't apply that tag again.

https://github.com/DeltaV-Station/Delta-v/blob/515c1dc3afdf1b327f672921c8c9e75c1f426712/Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml#L511-L513
https://github.com/DeltaV-Station/Delta-v/blob/515c1dc3afdf1b327f672921c8c9e75c1f426712/Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml#L559-L561

**Comment by DangerRevolution** [comment]
upstream issue: https://github.com/space-wizards/space-station-14/issues/27445

**Comment by pissdemon** [comment]
Fixed upstream, will be fixed here with next merge
