### ISSUE TITLE
CI issue: Railgun PR causes CI failure (linter and build&test)

### ISSUE THREAD

**Issue by pissdemon** [DeltaV-Station/Delta-v#1153]
Build and test error:   `----> Robust.Shared.Utility.DebugAssertException : Unknown tag: CannonRestrict`
Linter error: `Error: /Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Projectiles/railgun.yml(37,7)  PrototypeID CannonRestrict for type Content.Shared.Tag.TagPrototype at Line: 37, Col: 7 not found`

Caused by merge of #718

See:
- Build and test: https://github.com/DeltaV-Station/Delta-v/actions/runs/8883269474/job/24389768598
- Linter: https://github.com/DeltaV-Station/Delta-v/actions/runs/8883269487/job/24389768896?pr=1152

Relevant yaml section: 
https://github.com/DeltaV-Station/Delta-v/blob/b45b2cba58d78028fde807fe39e6b51afa6fb293/Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Projectiles/railgun.yml#L35-L37

**Comment by pissdemon** [comment]
The CannonRestrict tag is not referenced anywhere else in the codebase so it should probably just be removed.

**Comment by pissdemon** [comment]
More specifically this is caused by https://github.com/space-wizards/space-station-14/pull/26878 removing the CannonRestrict tag for restricting stuff from being shot from pneumatic cannons. That's a problem because there is no replacement. 

On master if you have the bad tag in it causes exceptions (I think it might cause the entity to be deleted too, wasting TC?) 

If you do remove the tag, instead of having to spend 21TC for the bundle with the Decimator, you can buy railgun ammo for 2TC and fire it from a pneumatic cannon which is very bad. I tested this with a master build and it works and one hit crits a naked Urist and two hit crits an officer. There is no replacement for the blacklist - they "fixed" the cannon blacklist issue by making it a 2x2 gridinv, but rods are 1x2 so two still fit in the cannon.

Also trying to pick a rod from a box causes:
```
[ERRO] system.actions: Failed to get action from action entity: box of rebar (2769/n2769, RailgunAmmoBag). Trace:    at System.Environment.get_StackTrace()
   at Content.Shared.Actions.SharedActionsSystem.TryGetActionData(Nullable`1 uid, BaseActionComponent& result, Boolean logError) in Content.Shared\Actions\SharedActionsSystem.cs:line 127
   at Content.Server.Store.Systems.StoreSystem.OnEntityRemoved(EntityUid uid, StoreRefundComponent component, EntRemovedFromContainerMessage args) in Content.Server\Store\Systems\StoreSystem.Refund.cs:line 18
...
```

**Comment by deltanedas** [comment]
manually add blacklist with the rods tag

**Comment by MilonPL** [comment]
The railgun got reverted so I guess this is resolved.
