### ISSUE TITLE
DV-atlas-atmos.yml spawns with a debug generator

### ISSUE THREAD

**Issue by Axionyxx** [DeltaV-Station/Delta-v#1167]
What it says on the tin. Might be more, this is just one that I know has it

https://github.com/DeltaV-Station/Delta-v/blob/e3d4adba0e485d85c2740b32d9d1bb25593e31fc/Resources/Maps/Salvage/DeltaV/DV-atlas-atmos.yml#L2003-L2009

**Comment by DangerRevolution** [comment]
should this be unmapped or can i just delete it out the .yml?

or replace it with a different prototype just raw in the .yml

**Comment by IamVelcroboy** [comment]
> should this be unmapped or can i just delete it out the .yml?
> 
> or replace it with a different prototype just raw in the .yml

Replace with the other small gen, the the one that radiates when you break it. I'm too tired to remember what it's called rn.

**Comment by therealDLondon** [comment]
> Replace with the other small gen, the the one that radiates when you break it. I'm too tired to remember what it's called rn.

The RTG?

**Comment by IamVelcroboy** [comment]
> The RTG?

Yeah, probably 😄 my brain hurts a little this morning
