### ISSUE TITLE
"Funny fire alarm on LH"

### ISSUE THREAD

**Issue by IamVelcroboy** [DeltaV-Station/Delta-v#1188]
## Description
![image](https://github.com/DeltaV-Station/Delta-v/assets/107660393/546301d9-a0ad-415b-b134-1babe0160b70)

**Comment by IamVelcroboy** [comment]
also 
![image](https://github.com/DeltaV-Station/Delta-v/assets/107660393/0ebe07ec-dab9-4b6f-8dd9-fccfd352046f)

**Comment by deltanedas** [comment]
the
