### ISSUE TITLE
Cryopods being rendered unuseable when multiple people attempt to use it.

### ISSUE THREAD

**Issue by SolStar2** [DeltaV-Station/Delta-v#1192]
##Description
Attempting to open a cryosleep pod UI causes people in the cryopods UI to close the UI. This leads to an issue where if multiple people are trying to use the cyopod UI it enters into a state that causes it to be unusable by anyone for the remainder of the round as the UI will afterwards automaticly close before anything can be done in it.

##Reproduction
I have not attempted to reproduce but speaking with others it seems to be an issue with UI's at the moment in general but in this case causes them to be unuseable.

##Screenshots
N/A

##Additional context
Other UI's have the same aformentioned issue but when interacting with cyropods it causes further issues

**Comment by pissdemon** [comment]
Have you tested it upstream? I don't think Delta did much to cryopods if anything at all so it's probably an upstream issue if I had to guess.

**Comment by DangerRevolution** [comment]
> Have you tested it upstream?

definitely need to test on Wiz first because Delta only made minor changes to Cryo (that I don't think work lol because you can still Cryo yellow-texters)

**Comment by SolStar2** [comment]
I tested it in leviathan and had no issue

**Comment by ghost** [comment]
Is this still an issue?

**Comment by SolStar2** [comment]
No longer an issue my bad!
