### ISSUE TITLE
Tortuga Has No Station Beacons

### ISSUE THREAD

**Issue by Nairodian** [DeltaV-Station/Delta-v#1212]
## Description
The Tortuga map appears to lack any Station Beacons or Navmap labels. (I don't think it was a bug at least, I don't have a dev environment for Delta-V.)

**Reproduction**
> Open map
> No station beacons inside
> Despair

**Screenshots**
![image](https://github.com/DeltaV-Station/Delta-v/assets/110078045/64864676-5fa2-4cfa-95ea-aec4831be5a0)

**Comment by rosieposieeee** [comment]
upstream issue with all beacons on all maps

**Comment by Nairodian** [comment]
> upstream issue with all beacons on all maps

Buh, okay yeah you could be right. I remember seeing, I think it was Submarine, with working nav points, but those could have been the way points instead of station beacons.

**Comment by deltanedas** [comment]
all maps have beacons this is an upstream issue with the text being nuked
