### ISSUE TITLE
diagnosis module missing from robofab?

### ISSUE THREAD

**Issue by DangerRevolution** [DeltaV-Station/Delta-v#1213]
## Description

Apparently nuked in https://github.com/DeltaV-Station/Delta-v/commit/9df7cb37c943b80f6f4167edfda90644b2e440a7

Reported in https://discord.com/channels/968983104247185448/1240941650130374697

The Diagnosus module was nuked from the Research tree, but is still a "dynamic recipe" (research locked) in the lathe, hence is inacessible except from looting Roundstart MedBorgs (Submarine)

**Additional context**

May be a Wizden issue, should still be here as MedBorgs that are **NOT** roundstart **CANNOT** get this module but **ROUNDSTART** borgs can (submarine)

**Comment by deltanedas** [comment]
i think it was nuked upstream

**Comment by ghost** [comment]
Tagging this as upstream issue because it looks like that sort of thing.

**Comment by deltanedas** [comment]
its not a thing anymore, treatment module has a scanner
