### ISSUE TITLE
Senior job loadout requirements are not representative of experienced players in departnments.

### ISSUE THREAD

**Issue by WarMechanic** [DeltaV-Station/Delta-v#1225]
![image](https://github.com/DeltaV-Station/Delta-v/assets/69510347/cf6263ff-092b-4e64-9db8-3fd55761f27a)

## Description
While senior gear is merely a cosmetic over normal gear (and it should stay that way), the label should be reserved for players experienced enough to reasonably teach less competent players mostly everything within said department. The causality only serves to differentiate Captain/Warden/HoS players from normal department roles. I'll probably run into a captain main misusing the label as an under experienced station engineer per se. Players misusing the senior label would diminish its perceptive value, which makes the point of differentiating yourself as a senior redundant.
I believe this issue could be resolved with a separate whitelist for senior players, although this would require https://github.com/space-wizards/space-station-14/pull/28085 to be merged upstream.

**Comment by Timemaster99** [comment]
I do agree with the sentiment over mastery of the role, but I don't think a separate whitelist for each role is equitable. This would leave staff in charge of judging "experience", which itself is a qualitative metric with no defined threshold between a regular and a senior. Playtime is a more impartial, easily automated metric.
I should also mention because I don't believe many are aware, that there is a 60 hour department playtime requirement on top of the whitelist for senior gear. This should rid any worry of a whitelisted player using the senior role without enough experience under their belt.

**Comment by WarMechanic** [comment]
How about a separate whitelist for all senior roles? I would like to whitelist to be a senior engineer, but have little interest in captain, hos or warden.

I personally wasn't aware about the hour requirement though, I thought it was 300 like atmos tech.

**Comment by Colin-Tel** [comment]
Let’s just make the senior gear a 100 hour requirement 😎

**Comment by DangerRevolution** [comment]
> How about a separate whitelist

When Wizden accept the PR to make whitelists seperate, atm it's just a bool.

**Comment by DangerRevolution** [comment]
> Let’s just make the senior gear a 100 hour requirement 😎

100 Hours doesn't correlate to being responsible & being a good teacher, as shown by the high-hour count LRP shitters in Delta

**Comment by Colin-Tel** [comment]
> > Let’s just make the senior gear a 100 hour requirement 😎
> 
> 100 Hours doesn't correlate to being responsible & being a good teacher, as shown by the high-hour count LRP shitters in Delta

I can’t think of any, can you start naming them? /j

**Comment by Carolyn3114** [comment]
> > Let’s just make the senior gear a 100 hour requirement 😎
> 
> 100 Hours doesn't correlate to being responsible & being a good teacher, as shown by the high-hour count LRP shitters in Delta

a whitelist doesn't really either

**Comment by DangerRevolution** [comment]
> > > Let’s just make the senior gear a 100 hour requirement 😎
> > 
> > 
> > 100 Hours doesn't correlate to being responsible & being a good teacher, as shown by the high-hour count LRP shitters in Delta
> 
> a whitelist doesn't really either

that's because any chimpanzee with a basic grasp of English and two thumbs can get whitelisted, not something fixable with PR's

**Comment by Carolyn3114** [comment]
so are you on the "against everyone" side?
