### ISSUE TITLE
Syndicate Traitor Roll Not Respecting Time Requirement

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#1235]
## Description
I've seen a number of players join for the very first time and roll syndicate. 

**Reproduction**
Join the server for the first time on a Traitor round, and cross your fingers.

**Screenshots**
![image](https://github.com/DeltaV-Station/Delta-v/assets/49795619/7e452f3d-c028-450c-9149-40a28b86eddd)
Full screenshot available in admin ahelp-relay at https://discord.com/channels/968983104247185448/975463515999584337/1242655033984549016

**Additional context**
It is supposed to have a 24 hour time requirement per https://wiki.delta-v.org/view/Traitor

**Comment by Lyndomen** [comment]
![image](https://github.com/DeltaV-Station/Delta-v/assets/49795619/9c631a2f-54f7-4f42-be15-1a2c78aae322)
The round in question (12150) also had the above gamerules running.

The round was initially a Survival round, and we ended up with 16 total Syndicate Agents.

**Comment by deltanedas** [comment]
upstream issue with sleeper agents i think

**Comment by MilonPL** [comment]
Fixed upstream at some point.
