### ISSUE TITLE
Slime ghost role description is contradictory

### ISSUE THREAD

**Issue by redmushie** [DeltaV-Station/Delta-v#1241]
## Description
Slime ghost role short description vs full description you get when you click "Join raffle" are not only vastly different but also contradictory.

## Reproduction
Be a ghost and click "Join raffle" on Slime role. See mismatched description.

## Screenshots
![SS14 Loader_fcynIbBc5B](https://github.com/DeltaV-Station/Delta-v/assets/82113471/f924985d-327e-4879-b69b-5eb585466989)

## Additional context
One states "friendly", other states "You are allowed to attack crew without provocation".

**Comment by Bonktrauma** [comment]
This has been a bug for awhile, I think it lumps the friendly slimes in with the non

**Comment by MilonPL** [comment]
Duplicate of https://github.com/DeltaV-Station/Delta-v/issues/908.
