### ISSUE TITLE
submarine southeast solars mv is cut off

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#1249]
## Description
![05:00:57](https://github.com/DeltaV-Station/Delta-v/assets/39013340/70aafe48-d706-44c0-9ea0-c134c11ec5b4)

cable terminal cuts it off, have to put the mv line in the middle

**Comment by IamVelcroboy** [comment]
Closing as Sub is not in rotation currently/will be reworked before it is again.
