### ISSUE TITLE
Nukies do not spawn

### ISSUE THREAD

**Issue by therealDLondon** [DeltaV-Station/Delta-v#1258]
## Description
Despite the server having chosen "Nukeops for secret" and the Nukie Planet loading in correctly, it seems that the nukies simply arent chosen

**Reproduction**
Get nukie gamemode selected with enough players. Wait for the server to load. Take a look a nukie planet - boom, no nukies

**Screenshots**

**Additional context**
We had a similar issue some time ago, unsure of the fix.

**Comment by DangerRevolution** [comment]
error log? or can only null do that?

**Comment by Axionyxx** [comment]
Code was broken by https://github.com/DeltaV-Station/Delta-v/pull/1238, will require an upstream merge to be fixed.

**Comment by Colin-Tel** [comment]
This is fixed as of the most recent upstream merge #1278
