### ISSUE TITLE
Detective can't install LogProbe after SecWatch was added

### ISSUE THREAD

**Issue by Remuchi** [DeltaV-Station/Delta-v#1259]
## Description

Basically that's it. I suppose it has a hardcap at 6 programs per PDA and trying to install it as sixth goes above it (as it can't create new "page" for new program)

**Reproduction**

1. Get Detective's PDA
2. Insert LogProbe cartridge
3. Try to install it.
4. It fails

**Screenshots**

https://github.com/DeltaV-Station/Delta-v/assets/72476615/cec5a400-352a-4d6f-af9f-215319036042

**Additional context**

Probably can't install it on other security PDAs as well

**Comment by deltanedas** [comment]
whys the limit so low theres clearly enough space for ~5 more programs without scrolling
