### ISSUE TITLE
Mission Senior ID unsuccessful

### ISSUE THREAD

**Issue by WarMechanic** [DeltaV-Station/Delta-v#1263]
## Description

Upon choosing Senior Engineer, shows up with Station Engineer and doesn't change to Senior Engineer for some reason, although I thought it was fixed.

**Reproduction**

Late-join with Senior Engineer ID in loadout, expect 'Senior Engineer' to appear in crew manifest.

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/69510347/98b1b96e-de68-41b1-964b-4aaa0ab928b5)

**Comment by Colin-Tel** [comment]
If you choose a Senior PDA in your station engineer loadout, it means that you're choosing to have the ID card of your job (station engineer) be placed in a Senior Engineer's PDA, meaning this is intended functionality.

**Comment by Timemaster99** [comment]
> If you choose a Senior PDA in your station engineer loadout, it means that you're choosing to have the ID card of your job (station engineer) be placed in a Senior Engineer's PDA, meaning this is intended functionality.

There was a PR to change this a while ago after discussion. See #1218

**Comment by Radezolid** [comment]
A bit of information I gathered while playing.
For some reason everytime I ready up on Periapsis I do get the Senior Engineer title change, while I only got it once on Apoapsis.
My wild guess is that it might have something to do with the pop at the moment of the assignation? I got no clue.

**Comment by Colin-Tel** [comment]
> A bit of information I gathered while playing. For some reason everytime I ready up on Periapsis I do get the Senior Engineer title change, while I only got it once on Apoapsis. My wild guess is that it might have something to do with the pop at the moment of the assignation? I got no clue.

This issue is present only when you **late join** as the role with the stuff in your loadout.

**Comment by WarMechanic** [comment]
I am working on this
