### ISSUE TITLE
Listening post causes Traitorloose

### ISSUE THREAD

**Issue by ghost** [DeltaV-Station/Delta-v#1275]
## Description

Alternative title is _"Antag Refactor broke the LP."_
Probably related to the Antagonist Refactor, and is liable to be like this or similar until a PR is merged with a fix to this - spawning in as a Listening Post operator does a few things now;
- You get objectives that would be on station, as a Listening Post Operative. Furthermore, when you spawn in as a Listening Post op, it activates the Traitor Game Rule, turning any round where LP is spawned into Traitor, even if it's survival.
- Listening Post Operatives get a 20 TC uplink, due to this, and this has a whole range of items including reinforcements, which also add the Traitor gamerule.

**Reproduction**

- Open up development environment
- Startround, do addgamerule PirateRadioSpawn
- Join as Listening Post Operator (LPO)
- Check character menu, actual objectives like a syndicate agent.
- Open uplink, 20 TC.
- Do endgamerule, Traitor is now a gamerule even if it was a Zombies, Nukeops, or Survival / Extended round. Not sure what this entails, but the game might start rolling traitors.

**Screenshots**

I have a video of this in action but it's too big for github - will edit this when it uploads.

**Additional context**

Largely these are unintended, regarding the way LP is set up and its ghost role rules. The source of this may have been fixed upstream, also, so it's worth it to wait until an upstream merge before trying to fix this. If it persists then this becomes valid.
This also locks in with #1258 and #1235 because they're all issues nested in the same thing, the Antag Refactor.

**Comment by deltanedas** [comment]
i have an upcoming rework that gives them their own role

**Comment by Bonktrauma** [comment]
if you get telgnosis as a lp op rn, and you use it, it resets crystals

**Comment by ghost** [comment]
Fixed by #1369; so, when that is merged, I will close this issue (or I guess Github will do it itself? We'll see.)

**Comment by deltanedas** [comment]
github will do it automatically because it has `fixes #ISSUE`
