### ISSUE TITLE
Map render bot stopped again

### ISSUE THREAD

**Issue by IamVelcroboy** [DeltaV-Station/Delta-v#1277]
## Description
Periodically it just stops working. In the past Debug would reset it or something. (I really don't know what they did)
Both Pebble and Shoukou are currently not showing up at all on the Map Viewer
Micro Station does not have an image in the Map Viewer yet

**Additional context**
Minor issue: It seems to cut off a few tiles on the far right side of some maps. Not a major issue but notable.

**Comment by Axionyxx** [comment]
Should be fixed again for now after I finish rerendering all maps
