### ISSUE TITLE
Esword sprites are broken

### ISSUE THREAD

**Issue by pissdemon** [DeltaV-Station/Delta-v#1285]
## Description
Esword sprites are currently broken when you activate the eswords.

**Reproduction**
Activate an esword, get error sprite.

**Screenshots**
Will add later.

**Additional context**
Reported by noctyrn

**Comment by Axionyxx** [comment]
https://github.com/DeltaV-Station/Delta-v/pull/1290 will fix this for now, until it can be properly re-reverted

**Comment by Tryded** [comment]
how do I properly revert it, I could probably just copy and paste upstream esword code again and call it a day

**Comment by ghost** [comment]
Is this still an issue? Or is it a non issue? If not I can close this.

**Comment by deltanedas** [comment]
fixed at some point
