### ISSUE TITLE
Entire screen went black

### ISSUE THREAD

**Issue by Ghagliiarghii** [DeltaV-Station/Delta-v#1291]
## Description

Entire screen went black for me and several other people around the same time on the shift before #12394 today on Delta-V Periapsis. Some talk about different timings for different people. Relogging fixed the issue.

**Reproduction**

No idea what caused this, need some admin to check logs for the server during this round.

**Screenshots**

Didn't take a screenshot but entire screen including UI was black, not as if the world was black (I couldn't see my toolbar or actions or anything either)

**Comment by Axionyxx** [comment]
Not enough information, sounds like a client side bug

**Comment by Ghagliiarghii** [comment]
I'm aware of the lack of information, it happened to several (5 or more) people at the same time so even if client side it may be caused by something server side
I'm hoping someone with access to logs can get more information
