### ISSUE TITLE
Ninja phase cloak broke (oopsie!)

### ISSUE THREAD

**Issue by ghost** [DeltaV-Station/Delta-v#1326]
## Description

Ninja's phase cloak broke a while ago, have no clue why. 

**Reproduction**

Be a Ninja.
Try to turn invisible with your high-tech phase cloak provided by the spider clan.
Fail.
Cry.

**Additional context**

This has been a lingering issue for a bit, surprised no one made a github issue about it. 
All signs seem to be pointing towards it not being an upstream issue with StealthComponent - I'd wager this has to do with its interaction with Invisibility somehow, as a psionic power. 
It seems to work on cobras, on boxes, on everything else that just goes invisible, but not people.

**Comment by deltanedas** [comment]
works in ninja/toggle refactor upstream so can probably just wait on that

**Comment by ghost** [comment]
There was an upstream merge since you said that and I'm pretty sure it's linked to the aging psionics shitcode and that, in fact, it's an us issue

**Comment by deltanedas** [comment]
more than likely related to psionic invis being broken

**Comment by deltanedas** [comment]
was fixed at some point
