### ISSUE TITLE
DeltaV PDAs Don't Show on Character

### ISSUE THREAD

**Issue by Nairodian** [DeltaV-Station/Delta-v#1336]
## Description
Any non-Wizard's Den PDA that uses it's own PDA sprite under the DeltaV directory won't show up when equipped.

**Reproduction**
Equip a Delta-V PDA, such as corpsman.
Fail to see equipped sprite.

**Screenshots**
![image](https://github.com/DeltaV-Station/Delta-v/assets/110078045/441723a2-76d5-4021-8bc1-7acbcd3c2fac)

**Additional context**
_I have spent the last hour looking at the YAML code and brute forcing fixes, I genuinely have no idea why it's like this._

**Comment by Bonktrauma** [comment]
Maybe they need to be in upstream files?

**Comment by Nairodian** [comment]
Oh my fucking god I think I figured it out never mind. I'll PR a fix here soon.
