### ISSUE TITLE
Justice chat is super hard to read

### ISSUE THREAD

**Issue by Timer-of-Popsicles** [DeltaV-Station/Delta-v#1338]
## Description
 The chat is very hard to read against the backdrop of the chat panel, especially for people like me who have a hard time telling close shades of colors apart

**Reproduction**
The justice chat in-game is the problem. so simply use the justice headset key

**Screenshots**
 Included. not super necessary but they help

**Additional context**
 Even if i didnt have trouble seeing shades of color apart, it would still be pretty hard to read, could we get a lighter shader that contrasts the background a little bit better?
![test](https://github.com/DeltaV-Station/Delta-v/assets/150315916/1d60b11b-3e6e-47dc-8e80-e9308747f6e2)

**Comment by ghost** [comment]
#1340 fixes this as shown there, and replaces it with a brighter shade of this; if that's an adequate shade of that color, then this issue can be closed.

**Comment by deltanedas** [comment]
yeah its much easier to read now
