### ISSUE TITLE
Justice Department doesn't have a lunchbox

### ISSUE THREAD

**Issue by DangerRevolution** [DeltaV-Station/Delta-v#1341]
## Description

They don't have Lunchboxes in their lockers

**Reproduction**

Look inside locker
No lunchbox, no snacks

**Additional context**

Every other department, even the Syndies have one.

**Comment by Bonktrauma** [comment]
This is outrageous!! How will they have their lunch break now??

**Comment by Timemaster99** [comment]
Wysi

**Comment by deltanedas** [comment]
wysi + wyci + L + ratio

**Comment by si0ci0yuan0shao0nu420** [comment]
Justice for our hungry justice!

**Comment by IamVelcroboy** [comment]
Weeks have gone by, and still, Justice starves because no one packed a lunch for them 😫
