### ISSUE TITLE
noob trap hammurabi singulo

### ISSUE THREAD

**Issue by WarMechanic** [DeltaV-Station/Delta-v#1351]
## Description

hammurabi has some sus wires that imply that an engineer should place emitters facing the inner containment fields which actually just causes a singuloose (a containment field is created that cuts containment in half, loosing). it has been represented on a map.

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/69510347/84e9aea7-7ce1-4ce3-9ec7-3d189246aee2)

**Comment by IamVelcroboy** [comment]
Was fixed a couple updates ago
