### ISSUE TITLE
prosecutor has security access

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#1357]
## Description
they can use sectech etc its not good
if the intent is to let them in the brig, brig access should be brought back and given to lawyers and sec
since having Security/Lawyer/Prosecutor isnt that good
or have it Security/Justice and anyone in the justice department can go into the brig not just prosecutor and attorney

**Comment by IamVelcroboy** [comment]
The second option is probably the best way to go. Prosecutor needs access to general sec for the same reasons lawyer does.

**Comment by deltanedas** [comment]
general sec means they can free prisoners and get security gear, thats not basic brig access

**Comment by IamVelcroboy** [comment]
I mean convert the sec/lawyer doors to sec/justice. Problem solved

**Comment by deltanedas** [comment]
yes
