### ISSUE TITLE
shoukou prosecutor office placement

### ISSUE THREAD

**Issue by UnicornOnLSD** [DeltaV-Station/Delta-v#1373]
## Description

Prosecutor doesn't have sec access anymore, their office behind sec access doors on shoukou, you can only get out of sec as prosecutor using the back door of your office.

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/149102472/37966935-efc2-4b63-9f83-b37babe53fb6)

**Comment by TadJohnson00** [comment]
Original mapper for the updated Shoukou security department. That whole plaza and the armoury-facing area is intended to _not_ be civilian-facing; no one without a full security clearance should be able to access the armoury desk. Ideally, one could swap around the prosecutor's office and the detective's outpost, which would wholly solve the issue.

**Comment by deltanedas** [comment]
the armoury desk is still sec access i think so it should be fine to use sec/lawyer access for the plaza itself

**Comment by TadJohnson00** [comment]
Correction: no one should be able to access the armoury desk including the windoors around it. Justice has access to the holding cells already through the front entrance, there is no reason for them to be in the _Security_ plaza when their job revolves around their office, the court, and the holding cells.
As before, I highly recommend just swapping the location of the prosecutor's office and detective's office. I can even map it myself.

**Comment by ghost** [comment]
Addressed this in the latest Shoukou hotfix, taking TJ's criticism into account because fuck, you're so right TJ. Closing this issue as a result.
