### ISSUE TITLE
deltav guns dont need wielding + missing wielded sprites

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#1375]
## Description
when upstream made most guns require wielding adjutant (and likely a lot of other deltav specific guns) werent updated with this. a 1 handed shotgun with large capacity is stronger than a bulldog so it should either be made to require wielding or be balanced with that in mind (price hike or a unique downside)

**Comment by WarMechanic** [comment]
ive started work on fixing this, but there'll be another issue in that the DeltaV guns don't have a wielding sprite

**Comment by TadJohnson00** [comment]
I'll resprite the adjutant Soon:tm: (probably after my security loadout PR goes through), add a wielded sprite for it and the Vulcan, as well as the Typewriter, Mk1, and other guns I've added to the game.
