### ISSUE TITLE
Strip menu does not function

### ISSUE THREAD

**Issue by CometVoid** [DeltaV-Station/Delta-v#1379]
## Description
the strip menu is completely unusable. this persists across rounds and game restarts/

**Reproduction**
Attempt to use the strip menu in any way. Insert or remove an object. the doafter bar appears and immediately vanishes

**Additional context**
Other players do not seem to have this bug. The only thing I can think of is a potential issue with the linux version of the game

**Comment by deltanedas** [comment]
was a misinput
