### ISSUE TITLE
Hunger scales far too quickly 

### ISSUE THREAD

**Issue by BellwetherLogic** [DeltaV-Station/Delta-v#1380]
## Description
Hunger, following #1302, now goes up FAR too quickly. How quickly? Eat-an-entire-pizza-by-myself-and-be-starving-five-minutes-later quickly. Stations are running completely out of food, Botany can't keep up with the demand, Chefs are going to Epi to have themselves sacrificed out of existential ennui, and as funny as that sounds it's incredibly unfun to have to spend half your shift searching for a rat to kill and eat because it represents the only edible biomass on the station. 

I get why this was tweaked upwards, but this is a solution that's caused far more problems than it's solved.

**Comment by Timemaster99** [comment]
Can confirm as a chef, two people was not enough to match the demand of an entire station.
I do not think it should be fully reverted, though; I enjoy the fact that people actually eat at the kitchen and have a need for chefs. The hunger rate should be toned down, but not back to its original state.

**Comment by BellwetherLogic** [comment]
I did the math after I posted this — the current rate is _thirty times_ faster than it used to be, per the numbers given in the PR, and that seems way out of whack. I think even twice or three times the old rate would still steer people to the kitchen much more than hunger used to and wouldn't result in this new starvation meta. (At least we don't take damage for it anymore, or we'd have had mass casualties from hunger in every shift yesterday.)

edit: I just did some more math: a decay rate of 0.05 means you drop 1 every 20 seconds, meaning you go from fully satiated hunger to completely starving (assuming a scale of 100, I haven't checked the code, but it fits with my own in-game experiences) in _twenty minutes_. That's six cycles of gorge-to-starvation per shift. That's way too high. No wonder Hydro and the Kitchen can't keep up.

**Comment by therealDLondon** [comment]
@Colin-Tel

**Comment by deltanedas** [comment]
the old rate was ~4x faster now its ~2x faster

```cs
public float BaseDecayRate = 0.035f; //DeltaV: changed from 0.01666666666f
```

**Comment by Colin-Tel** [comment]
yeah, the above change is already addressed. My b, didn't know this was even an issue that was made.
