### ISSUE TITLE
Edge's funny distro pipes at Epistemics.

### ISSUE THREAD

**Issue by Radezolid** [DeltaV-Station/Delta-v#1385]
## Description
Funny pipes in front of Edge's epistemics department should be removed and replaced by T pipe.
I also noticed that only at EPI the distro pipes turn gray-blueish? only at EPI's distro pipes.

This problem is making engies that dont know about this problem find out that after EPI goes boom they can't get the room to repressurize.

**Reproduction**
1. Grab T-Ray.
2. Walk to EPI's front.
3. Find funny pipes.

**Screenshots**
![image](https://github.com/DeltaV-Station/Delta-v/assets/170836000/6d84182f-6f45-4f0b-9ce6-d1fb3ccadbf2)

**Additional context**
No.

**Comment by therealDLondon** [comment]
As Edge's maintainer, I can say this is going to be fixed in an upcoming fix sometime next week,
Not immediate, but soon.

I am aware of the issue, however, thank you

**Comment by IamVelcroboy** [comment]
Was this fixed in last update?

**Comment by IamVelcroboy** [comment]
I completely forgot about this. I'm assuming it was fixed w/recent update? @therealDLondon

**Comment by Radezolid** [comment]
I forgot to close this, it has been fixed.
