### ISSUE TITLE
Atmos pumps may need power soon.

### ISSUE THREAD

**Issue by WarMechanic** [DeltaV-Station/Delta-v#1388]
## Description

If this PR gets merged https://github.com/space-wizards/space-station-14/pull/28995 then maps should be consolidated to make sure that LV cables are routed throughout Atmos, atleast along the waste line where pumps would be.

**Comment by Colin-Tel** [comment]
Is there any example of atmos that *doesn't* have LV?

**Comment by IamVelcroboy** [comment]
I'd say, this isn't really an issue until it's an issue. Which is whenever we merge upstream again, at which point we can check each map.

**Comment by WarMechanic** [comment]
> Is there any example of atmos that _doesn't_ have LV?

off the top of my head i think any atmos that uses pumps in their space radiators will need to route lvs in space.

**Comment by deltanedas** [comment]
will update shoko stuff

**Comment by IamVelcroboy** [comment]
Reopen if there are any specific maps with this issue.
