### ISSUE TITLE
some asterisk head rooms have no dressers

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#1408]
## Description
at least the ce is missing

might be fixed by the current asterisk pr

**Comment by Colin-Tel** [comment]
I was told this wasn't a problem so long as the cloaks are present, as they are a possible steal objective.

**Comment by deltanedas** [comment]
missing mantles for people that are promoted / dont have loadouts set

**Comment by therealDLondon** [comment]
> missing mantles for people that are promoted / dont have loadouts set

*uniform printer whirring sound*
