### ISSUE TITLE
Nuclear explosions are pretty funky

### ISSUE THREAD

**Issue by noctyrnal** [DeltaV-Station/Delta-v#1431]
## Description

Nuke explosions dont seem to do nearly enough damage, seems instead they just erase most entities in a small radius and thats it.

**Reproduction**

1- Set off La Bomba
2- Nuke does no big bomba

**Screenshots**

![image_2024-06-25_201113861](https://github.com/DeltaV-Station/Delta-v/assets/99278536/d7ad1cf9-eda8-4ec2-a8e9-920da6fbfd0a)

Green was where the nuke was, red was how far the explosion went.

**Additional context**

**Comment by deltanedas** [comment]
explosions in an enclosed area seem to have been nerfed indirectly somehow
a maxcap in a 2x2 closed room wont spread past the walls of the room, but if it has an open door the entire area is destroyed

**Comment by ghost** [comment]
As far as I'm aware this has been a long standing issue with Arena's nuke in particular just nuking all entities and not nuking the floor. I wonder why...

**Comment by MilonPL** [comment]
Can't reproduce, haven't seen it happen for a while.
