### ISSUE TITLE
mass sleep can instantly be woken up from

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#1433]
## Description
its basically a psychic pie throw

**Comment by DangerRevolution** [comment]
recreation? any PR's that could've caused this?

**Comment by deltanedas** [comment]
i believe it appeared after an upstream merge that changed sleep code

**Comment by DangerRevolution** [comment]
> i believe it appeared after an upstream merge that changed sleep code

:(

**Comment by deltanedas** [comment]
also another bug it raises glimmer even if nobody is slept by it + has full cooldown too

**Comment by UnicornOnLSD** [comment]
my absolutely overpowered instant stun click power isn't overpowered anymore ? impossible.

**Comment by Squishy77** [comment]
I made a pr that added nospheirc zap as the same rarity as mass sleep, it would do a stun baton stun on one target instead of many, I feel like this could balance it out in a way.

**Comment by ghost** [comment]
will be fixed by #1649 when that's done
