### ISSUE TITLE
Shipyards are bugged 

### ISSUE THREAD

**Issue by Squishy77** [DeltaV-Station/Delta-v#1435]
## Description
When you open the shipyard console's Ui it displays no ships to buy. 

**Reproduction**
Open the Ui on the shipyard.

**Screenshots**
![image](https://github.com/DeltaV-Station/Delta-v/assets/165165480/d10ee27a-be42-42a4-ad4d-b28209b7b169)

**Additional context**
No idea what happened

**Comment by Squishy77** [comment]
Its like this everyround

**Comment by deltanedas** [comment]
me when pro api IsWhitelistPass() != !IsWhitelistFail() because they both return false if its null
