### ISSUE TITLE
Justice stamps are not properly suffixed

### ISSUE THREAD

**Issue by DangerRevolution** [DeltaV-Station/Delta-v#1436]
## Description

Resources/Prototypes/DeltaV/Entities/Objects/Misc/rubber_stamp.yml

Justice stamps are not properly tagged "DO NOT MAP" like any other stamp

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/e8681a1b-38d8-4f92-be4a-1f0780b5ea4d)

**Comment by IamVelcroboy** [comment]
Would have taken just as much time to PR the suffix edit. 😋

**Comment by DangerRevolution** [comment]
> Would have taken just as much time to PR the suffix edit. 😋

Maybe :)

**Comment by Timemaster99** [comment]
Ok
