### ISSUE TITLE
Nukie mouse gets antag objectives.

### ISSUE THREAD

**Issue by Radezolid** [DeltaV-Station/Delta-v#1438]
## Description
Title.

**Reproduction**

-Call mice with "Mouse operative reinforcement teleporter".
-Take the role of the mice.
-Now you got objectives.

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/170836000/882e507f-3359-4704-9e6d-5da7102849b1)
![image](https://github.com/DeltaV-Station/Delta-v/assets/170836000/08752d12-4061-4672-8fd5-5b219df6d523)

**Additional context**
None.

**Comment by WarMechanic** [comment]
how do you steal the CMO's hypospray with no hands

**Comment by deltanedas** [comment]
remove le autotraitor

**Comment by MilonPL** [comment]
Autotraitor evil, gone.
