### ISSUE TITLE
tortuga issues

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#1475]
## Description
- entire teg setup is dogwater and hot loop doesnt even function because of how anchoring works
- there is no gas pump for limiting distro pressure
- salv dock should be flipped, if you dock something it basically blocks cargo shuttle from docking
![02:55:38](https://github.com/DeltaV-Station/Delta-v/assets/39013340/229b51fe-abd0-49be-9e8e-42dda0ec2000)
- possibly overlapping lights, maybe someone built it midround
![02:56:28](https://github.com/DeltaV-Station/Delta-v/assets/39013340/611c3403-df49-4d70-a838-634c7ce6f806)

**Comment by IamVelcroboy** [comment]
>     * entire teg setup is dogwater and hot loop doesnt even function because of how anchoring works

What do you mean "because of how anchoring works?"

>     * there is no gas pump for limiting distro pressure
![image](https://github.com/DeltaV-Station/Delta-v/assets/107660393/279e84f9-71a0-43bb-95da-ba61218c4db1)

>     * salv dock should be flipped, if you dock something it basically blocks cargo shuttle from docking

This dock is only meant for salv to have an alternative way to load the cargo shuttle, by moving the shuttle between the 2 docks. It was not intended for any salvage shuttles.

**Comment by IamVelcroboy** [comment]
Although, I wouldn't be opposed to adding docking airlocks to the other side 
![image](https://github.com/DeltaV-Station/Delta-v/assets/107660393/68a35bb6-7e7a-48cd-9590-037eeafe5b9e)

**Comment by IamVelcroboy** [comment]
>     * possibly overlapping lights, maybe someone built it midround

Appears to be a midround goof 
![image](https://github.com/DeltaV-Station/Delta-v/assets/107660393/b98b8ae8-57bb-46c8-9ac2-e6e4c3f35c71)

**Comment by Radezolid** [comment]
> > ```
> > * entire teg setup is dogwater and hot loop doesnt even function because of how anchoring works
> > ```
> 
> What do you mean "because of how anchoring works?"

They mean this:
![image](https://github.com/DeltaV-Station/Delta-v/assets/170836000/93d4d224-b6fa-42de-9238-d4282f07975f)

![image](https://github.com/DeltaV-Station/Delta-v/assets/170836000/6f0f3c1a-61d0-4c7f-bee1-a5d4372a7c64)

That connector port can't be used due to the plasma directional window.

> > ```
> > * there is no gas pump for limiting distro pressure
> > ```
> 
> ![image](https://private-user-images.githubusercontent.com/107660393/347018570-279e84f9-71a0-43bb-95da-ba61218c4db1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NDM0MTEsIm5iZiI6MTcyMDU0MzExMSwicGF0aCI6Ii8xMDc2NjAzOTMvMzQ3MDE4NTcwLTI3OWU4NGY5LTcxYTAtNDNiYi05NWRhLWJhNjEyMThjNGRiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxNjM4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWJmMGRiYjMzZjAyNTExN2IxZGVmYjI0OGRhYTdiY2U3MjY0ZmNlOTBiYTY2MWJkNGRmYjM3NjdiODdhNDcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kt5Sj59apa2OFIqmt6lXvkxKYanXAzdOCmOhDk4thcI)

That's... for pumping stuff into distro, that wont limit the pressure in distro.

**Comment by IamVelcroboy** [comment]
> That connector port can't be used due to the plasma directional window.

Oh Jesus, that's so cancer. I thought there was a fix for that months ago. 😕

**Comment by deltanedas** [comment]
that highlighted pump is A) useless in 99.99% of rounds B) not what limits distro pressure its for refilling it with a can

ideally tortugamos would just be 4 stacks of steel and a blank slate to save on welding

**Comment by IamVelcroboy** [comment]
> that highlighted pump is A) useless in 99.99% of rounds B) not what limits distro pressure its for refilling it with a can

I see that now 

> ideally tortugamos would just be 4 stacks of steel and a blank slate to save on welding

Nah, I'm not going to do that
