### ISSUE TITLE
Micro station salvage chunks sometimes merge with station

### ISSUE THREAD

**Issue by Colin-Tel** [DeltaV-Station/Delta-v#1477]
## Description

On occasion, the stuff the salvage magnet pulls in will have the stuff extremely close to, if not intersecting the station

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/113523727/aad89f61-4723-442f-a7bc-eb045f1ae5ba)

**Additional context**

Probably just need to move the magnet higher.

**Comment by IamVelcroboy** [comment]
Is this remedied? Looks like it was supposed to close but didn't for some reason

Edit: Oh, I'm dumb. I didn;t merge the map update yet 🤓
