### ISSUE TITLE
Syndicate Recruiter needs Lawyer playtime

### ISSUE THREAD

**Issue by EkrellX** [DeltaV-Station/Delta-v#1483]
## Description
The new Syndicate Recruiter antag requires 60 minutes of playtime as a lawyer, which doesn't exist anymore, preventing people who never played it from getting the role ever.

**Reproduction**
Get into a game
Wait for Syndicate Recruiter to pop up
Be sad as you can't enter the raffle because lawyer playtime prevents you from doing so

**Screenshots**
I'll update if I get the chance to

**Additional context**
Simply switch it to the justice department, attorney, or civilian playtime, or preferably remove it outright and just keep as general playtime.

**Comment by Timemaster99** [comment]
Attorney is still referred to as Lawyer internally. It is asking for Attorney playtime

**Comment by deltanedas** [comment]
prosecutor clerk and cj have their own ids, attoeney is just lawyer reskin
