### ISSUE TITLE
Many maps is missing a Bingus spawner

### ISSUE THREAD

**Issue by Colin-Tel** [DeltaV-Station/Delta-v#1504]
## Description

It's a thief objective >w<

**Reproduction**

No

**Screenshots**

![image](https://github.com/user-attachments/assets/1fb2d0e5-2b35-4359-a63d-85399c1ce8c6)

**Additional context**

Discord user `boodds` reported they couldn't greentext because of this and they're really sad so I did this for them because I'm a nice guy. 🙂

**Comment by IamVelcroboy** [comment]
Edge, Glacier, Micro, and Pebble are the only maps that have Bingus mapped currently

**Comment by IamVelcroboy** [comment]
No one maps Bingus 😄

But that's because I always just use the random cat spawner that has a chance to spawn Bingus...which brings up another issue when multiple Bingus on station...

Seems to me the objective should really be checking for the entity first before assigning it...coder issues

**Comment by IamVelcroboy** [comment]
Made [this ](https://github.com/space-wizards/space-station-14/pull/30504) PR upstream. Will fix if merged (and all maps have a cat spawner).

**Comment by IamVelcroboy** [comment]
The above PR was merged. So, I'm going to close this. We can then assess the maps to make sure hey have either 1 of the named cats mapped or the named cat spawner mapped. It will no longer need to be specifically Bingus after we merge upstream.
