### ISSUE TITLE
Cargo techs on glacier can't open the shuttle airlocks

### ISSUE THREAD

**Issue by OmegaZip2** [DeltaV-Station/Delta-v#1506]
## Description
On Glacier, cargo techs can't open the airlocks to get to the cargo shuttle when it docks. Salvage crew has access, though.

**Reproduction**
join as cargo tech
dock cargo shuttle
cry.

**Comment by Colin-Tel** [comment]
probably still has the old external airlocks with externals access, back when quartermaster had Externals.
