### ISSUE TITLE
chase module is not researchable

### ISSUE THREAD

**Issue by DangerRevolution** [DeltaV-Station/Delta-v#1521]
## Description

title, will expand when home

**Reproduction**

research it
can't fabricate

**Comment by DangerRevolution** [comment]
I really need help with this, I cannot seem to re-produce the issue on a local build. Any reproducable way to do this would be mega mega appreciated :)))

**Comment by deltanedas** [comment]
theres a test that checks all research items can be made in some kind of lathe, if this is 100% correct that wouldve failed

**Comment by DangerRevolution** [comment]
I cannot reproduce this locally; plus above ^

I also cannot reproduce Borgs dying of cold; and it should be impossible as inorganic mobs do not have a temperature component. Going to close this as not reproducible.

My advice is to try refresh the Sci server you are using the printer from

**Comment by DangerRevolution** [comment]
Borgs dying of cold is confirmed to be a false issue; the actual issue with Borgs dying on glacier is with Borg Feet and is a Wizden issue
