### ISSUE TITLE
Glacier has a set of doors that have no atmosphere

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#1550]
## Description
Tinyfans are keeping space at bay in securityland, the door to the Security Spa starts with no air, and those fans keep it that way.

**Reproduction**
Play Glacier, stand in the funny doors, die

**Screenshots**
![image](https://github.com/user-attachments/assets/abca4b79-5199-4638-822c-517b56be0a71)

**Additional context**
thanks

**Comment by Colin-Tel** [comment]
Tiny fans do this. It's like standing in a holofan.

**Comment by jimmy12or** [comment]
would the fixgridatmos command fix that?

**Comment by Colin-Tel** [comment]
> would the fixgridatmos command fix that?

Even if you were to do that and atmos was put onto the tile, the atmos would never be replaced because it can't pass from adjacent tiles onto the tile with the tiny fan.

So as far as I understand it, the tiny fan doors will never lose this problem unless something changes on a fundamental level with how tiny fans function.

**Comment by jimmy12or** [comment]
> > would the fixgridatmos command fix that?
> 
> Even if you were to do that and atmos was put onto the tile, the atmos would never be replaced because it can't pass from adjacent tiles onto the tile with the tiny fan.
> 
> So as far as I understand it, the tiny fan doors will never lose this problem unless something changes on a fundamental level with how tiny fans function.

While it won't be replaced, at least it wouldn't be spaced?

**Comment by DangerRevolution** [comment]
Why does a Sauna have tiny fans? Just turn the heating up if it's getting cold?

**Comment by deltanedas** [comment]
so the heat doesnt spread out
this would be fixed if directional tiny fans are merged

**Comment by DangerRevolution** [comment]
> so the heat doesnt spread out this would be fixed if directional tiny fans are merged

does the door not keep heat in?

**Comment by deltanedas** [comment]
no because doors open :trollface:

**Comment by DangerRevolution** [comment]
> no because doors open :trollface:

Then keep them closed :trollface:

**Comment by IamVelcroboy** [comment]
This is just how it works until we get directional fans from upstream. Closing as there isn't much we can do until then.
