### ISSUE TITLE
Butlertron needs its hitbox reduced

### ISSUE THREAD

**Issue by IamVelcroboy** [DeltaV-Station/Delta-v#1559]
## Description
Takes up the whole tile, 😃

**Reproduction**
See screenshot

**Screenshots**
![image](https://github.com/user-attachments/assets/d8621e40-2d60-416b-ba79-8ee3659ebb95)

**Additional context**
Easy fix

**Comment by EquanimityX0880** [comment]
I looked at R.Sh.PhysicsComponent and saw that the Butlertron ( named "roboisseur" in source) has a CollisionLayer of 20. Air canisters have a CollisionLayer of 85. 

If the Butlertron's CollisionLayer was set to 85, the resulting bounding box would likely suit the Butlertron more. Here's an image:

![image](https://github.com/user-attachments/assets/dfc832b8-2630-4386-887e-5bb30ce3bd60)

However, the only roboisseur.yml I found in Source does not involve bounding boxes. I actually can't find anything that mentions the Roboisseur's bounding box, or how collisionlayers are set.

![image](https://github.com/user-attachments/assets/53b43db8-7381-466c-a963-ae860e46d1cb)
Note: Using the Everything tool, I searched: "C:\Users\MoneyGang\Desktop\Delta-v\ content:roboisseur"

I'm pretty new to all this, so of course I'm starting with Priority 4.

**Comment by IamVelcroboy** [comment]
It needs something like(that's from vending machines) and then the numbers need to be tweaked to fit the butlertron
```yml
 - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.25,-0.45,0.25,0.45"
```
