### ISSUE TITLE
Syndicate Carp Suit Backslot unavailable 

### ISSUE THREAD

**Issue by Avalon-Proto** [DeltaV-Station/Delta-v#1561]
## Description
The new carpsuit from upstream is unable to use its Backslot. Even though it is a space capable EVA suit
**Reproduction**
- Get Carpsuit
- Put it on
- Unable to use Backslot for 02 tanks
- Cry
**Screenshots**
No screenshots

**Additional context**
Issue likely arises from the fact that the back slot is not automatically open for various other clothes options as that was disabled here, but I believe the carpsuit should be able to have an O2 tank mounted on the back of anything else that can go on a backslot

**Comment by DangerRevolution** [comment]
>new carpsuit from upstream

>Issue opened in Delta-V repo

**Comment by Avalon-Proto** [comment]
> > new carpsuit from upstream
> 
> > Issue opened in Delta-V repo

Ysee I opened it here cause I'm pretty sure in Delta we messed about with what can and can't have back slots. I'm fairly certain that upstream any outwear can use the backslot

**Comment by deltanedas** [comment]
yes its because the backslot pr isnt cherry picked

**Comment by Avalon-Proto** [comment]
> yes its because the backslot pr isnt cherry picked

Think you can fix this for us then, would love to not have to carry my oxy tank while wearing the carpsuit

**Comment by ghost** [comment]
Was the backslot cherrypicked? If so, this can be closed.
