### ISSUE TITLE
"Save Item Location" not working

### ISSUE THREAD

**Issue by FoxStellar** [DeltaV-Station/Delta-v#1607]
## Description

Attempting to use the "Save Item Location" keybind in your backpack or other grid inventory currently does not work.

**Reproduction**

1 - Make sure you're keybind is set, and then press that keybind while hovering over an item in a grid inventory
2 - Take the item out of the grid inventory and put it back in
3 - See the item hasn't returned to the location it was in when you pressed the "Save Item Location" keybind while hovering over it

**Screenshots**

The keybind location in the Controls menu
![image](https://github.com/user-attachments/assets/1b174d6f-b29b-4433-a451-8edb11d9726a)
where I want my pickaxe to be
![image](https://github.com/user-attachments/assets/96c0255e-7788-448e-889a-98263ed0448c)
Showing that the yellow "saved location" highlight isn't showing up
![image](https://github.com/user-attachments/assets/00861216-b3ad-4833-a90d-a0748534f9c8)
Showing that the pickaxe did not go to the correct location
![image](https://github.com/user-attachments/assets/57f4154d-a8a3-4f74-96f5-0a3bf38224b8)

**Comment by deltanedas** [comment]
https://github.com/space-wizards/space-station-14/issues/30947

**Comment by Jazun** [comment]
Is the fix for this being added to DeltaV yet honestly it's a nightmare

**Comment by deltanedas** [comment]
open for 2 weeks upstream might just early merge it here

**Comment by Radezolid** [comment]
> open for 2 weeks upstream might just early merge it here

Please do, it's a great QoL.
