### ISSUE TITLE
Game events dont run

### ISSUE THREAD

**Issue by therealDLondon** [DeltaV-Station/Delta-v#1608]
**Description**
Mid-game events just dont happen, even when added by addgamerule
Traitors and the other gamemode-essential events run fine, but everything else is stuck in (pending)
Survival is now greenshift

**Reproduction**
Start server
Try to run event, or wait for the schuduler to do a thing
Weep

**Screenshots**
![image](https://github.com/user-attachments/assets/59bd95e6-18a7-4081-af32-30b36ac2704f)

**Additional Context**
Happened after upstream merge

I put this issue in the upstream repo by accident and realised my mistake, oh god, kill me now

**Comment by MilonPL** [comment]
Fixed by https://github.com/DeltaV-Station/Delta-v/pull/1609.
