### ISSUE TITLE
The Hive stations "Naked zone"

### ISSUE THREAD

**Issue by NightBirby** [DeltaV-Station/Delta-v#1612]
## Description

During a recent round we experienced a area were if you walk around in inside it would make everything naked on your character as well as making you invisible.

**Reproduction**

walking in and out would cause this issue but I'm unsure if this is on each roumd of the map.

[**Screenshots**
] (https://drive.google.com/file/d/1SoEqdmgzZ7giUrW5K4xlhsgs5hYqqifw/view?usp=sharing) A video of the bug

**Additional context**

nothing further at this time.

**Comment by IamVelcroboy** [comment]
That's gotta be a clientside thing.

**Comment by NightBirby** [comment]
Its not others experienced it as well

**Comment by MilonPL** [comment]
PVS issue likely caused by a bad entity affecting 1/4th of the chunk, server-side, one round only.

**Comment by therealDLondon** [comment]
Turns out the bug was 99% an accident on behalf of administration

**Comment by IamVelcroboy** [comment]
> Turns out the bug was 99% an accident on behalf of administration

*Shakes fist in the air aggressively at the badmin* 😋
