### ISSUE TITLE
Mouse Reinforcement thingys summon people

### ISSUE THREAD

**Issue by AsprinNugget** [DeltaV-Station/Delta-v#1613]
## Description
 Mouse Reinforcement Beacon things summon human Reinforcements

**Reproduction**
I just used a mouse beacon, set it to spy *i think* and I got a person

**Comment by therealDLondon** [comment]
Hi, Ill have to ask that you do include more detail in your issue, especially what the issue is, otherwise there isnt much we can do

**Comment by AsprinNugget** [comment]
IT DIDNT WORK AAAAAAHHHH

**Comment by DarkenedSynergy** [comment]
This seems to be referring to the new syndicate reinforcement UI opening on the mouse reinforcement radio.

https://github.com/user-attachments/assets/177e297d-d2ed-4671-9ce3-0233ccc090f9



> ## Description
> Mouse Reinforcement Beacon things summon human Reinforcements
> 
> **Reproduction** I just used a mouse beacon, set it to spy _i think_ and I got a person

**Comment by deltanedas** [comment]
needs to not parent the human one, or else use new method of selecting reinforcement type and havei t just be 1 mouse

**Comment by DarkenedSynergy** [comment]
> needs to not parent the human one, or else use new method of selecting reinforcement type and havei t just be 1 mouse

Thought so, should be fixed in
https://github.com/DeltaV-Station/Delta-v/pull/1617
