### ISSUE TITLE
Lighthouse Clown Room uses Theater access

### ISSUE THREAD

**Issue by Avalon-Proto** [DeltaV-Station/Delta-v#1616]
## Description
The clown room on lighthouse uses Theater access instead of if Clown access as it should

**Reproduction**
1- Spawn as Mime/Musician 
2- walk to clown room
3- Door opens to your access

**Screenshots**

**Additional context**
I bring this up because yesterday during a nukie round. A clown thief had their round ruined by a musician leading me, the HoS, to their stash of stolen goods and contra in their room. As I feel this was unfair, I wish for the clown room to be private to the clown

**Comment by portfiend** [comment]
~~if you guys change this, you should also move the autodrobe out of the clown's room, unless there is another one on the station already~~ oh hey there's one in the theater nevermind
