### ISSUE TITLE
Camera orientation flips when standing on disappearing salvage debris

### ISSUE THREAD

**Issue by Maezel** [DeltaV-Station/Delta-v#1618]
Since the upstream merge on july 24th I've noticed that I and other salvagers get lost on the way back to the station more often and when I make it back my orientation is completely off from how I left the station, more than can be explained by just the auto-adjust when stepping onto a piece of debris, fairly consistently a full 180 degree flip. It's difficult to see or even capture this happening as obviously there's _literally nothing_ out there to give a frame of reference, but at least once I have managed to be close enough to a fellow salvager to watch my perspective twist 90 degrees the moment the debris disappears.

It seems like you can avoid it by stepping off the wreck before it goes, but I'd need to test that out more.

**Comment by deltanedas** [comment]
this has been a thing forever, it aligns you with the map
not a deltav issue

**Comment by Maezel** [comment]
Okay then something's fucked with the map because I consistently get flipped around in completely random directions

**Comment by deltanedas** [comment]
the map != the station
