### ISSUE TITLE
There are some places where you can get stuck on Glacier

### ISSUE THREAD

**Issue by dekigangsta** [DeltaV-Station/Delta-v#1621]
## Description
It is possible to get stuck between 2 solid objects (afaik you can get very easily stuck if you somehow nudge yourself between 2 trees or as you can see in the gif)

**Reproduction**
Find a tree where its tight and close to another object, run to some extent and wiggle around (currently possible in gif and between few trees near bonfire area)

Person who is stuck can be unstuck with help from another person by pushing them out

**Screenshots**
![asdf-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/070fbff8-ec64-49e6-8438-0c54930c8881)

**Additional context**
this would Really suck if it happens to a mute person Please fix thanks
also this warrants as a removal for this map (Obviously)

**Comment by pissdemon** [comment]
Should be fixed but keep in mind trees can be destroyed by meleeing with bare hands or many common objects, they aren't really resistant to damage at all.

**Comment by IamVelcroboy** [comment]
@deltanedas nudge these over a pixel or 2 next update I guess 🤷🏼‍♂️

**Comment by MilonPL** [comment]
The hitbox for trees is smaller now so.
