### ISSUE TITLE
trinkets from loadout require a bag 

### ISSUE THREAD

**Issue by MilonPL** [DeltaV-Station/Delta-v#1622]
## Description

Prisoners don't spawn with their trinkets because they don't get a bag so AAC tablets and stuff doesn't work.

**Reproduction**

\>select any trinket from prisoner loadout
\>spawn in
\>FUCK

**Additional context**

Broken by the last upstream merge, used to spawn on top of cryopods, got trolled by "De-duplicate loadout gear (#30341)" probably

**Comment by portfiend** [comment]
~~normally, if you have an item that does not slot into your loadout (for example: a job that default wears a neck item, but you also equip a loadout neck item over it), it will drop the item onto the ground where you spawn. if it doesn't do the same for trinkets we might need to have to code it in to specifically do that~~

always read posts kids

**Comment by deltanedas** [comment]
would be easiest to give prisoners bags roundstart
