### ISSUE TITLE
Tortuga Medbay issues

### ISSUE THREAD

**Issue by NightBirby** [DeltaV-Station/Delta-v#1644]
## Description

This bug or error on the map makes it so you cannot place items or right click within the back area where med beds are. this prevent med locker and cryobeds to be placed within that area. It also makes it so if you have the med locker near that area it is impossible to select meds from the locker because you need to right click to select which on you need,

**Reproduction**

This is a constant on the map.
**Screenshots**

https://drive.google.com/file/d/1B9D3xUwDsnX_Kc1S_fkk18liWUZRXWFG/view?usp=sharing
Video of the issue 

**Additional context**

**Comment by Colin-Tel** [comment]
The heck is “Station QT-952”

**Comment by IamVelcroboy** [comment]
Tested this on my end and I can't reproduce. RC is working fine for me.

**Comment by NightBirby** [comment]
Me and others have this happen every time, even when we remove the glass it doesn't let us right click anywhere.
<img width="1919" alt="Screenshot 2024-08-17 144717" src="https://github.com/user-attachments/assets/7d504ac0-a3cb-4967-b89d-32a96115ec0c">

**Comment by IamVelcroboy** [comment]
If you can get more reports, even ahelp during the round, maybe an admin can look into if something is erroring. I'm not sure what else I can do from my end if I can't reproduce it.
 
https://github.com/user-attachments/assets/d6fc8c94-d067-44de-8af1-722a9f4ac349

**Comment by NightBirby** [comment]
Once the glass is removed it seems to help now, I think because the glass is technically a a whole block its not letting me place place next to that window or let me right click. just a theory though. I'll make a help ticket in game when it happens again

**Comment by IamVelcroboy** [comment]
Yeah, the glass might prevent you from anchoring on that tile. You should still be able to move onto it but 🤷‍♂️

**Comment by IamVelcroboy** [comment]
I'll leave this open for another week. If you get any additional context, report back. If it's just the glass preventing anchoring, I'm going to chalk that up to a coding issue, not a mapping issue and close. Thanks for the report though.
