### ISSUE TITLE
Artifact scanner does not display correct node

### ISSUE THREAD

**Issue by OmegaZip2** [DeltaV-Station/Delta-v#1656]
## Description
When scanning an artifact, the console might start displaying the same node (so for example. TRIGGER: Magnetic waves, Reaction: Metaphysical displacement) which when you try to trigger it, obviously doesnt work (because the real node is different)
**Reproduction**
No idea. Might have to do with metaphysical displacement?

**Screenshots**

**Additional context**
this was fixed by wrenching the artifact scanner

**Comment by Radezolid** [comment]
I think that's a upstream bug that the artifact scanner doesn't update the fact they got a new artifact on top.

Fixes I saw are:
- You can remove the artifact from the place and return it on top of the scanner or anchor then unanchor it.
- Check for if the you got two artifact scanners linked to one console.

**Comment by deltanedas** [comment]
upstream funkiness specifically when theres 2 artifacts and you take one off
