### ISSUE TITLE
Metashield not mentioned in rules

### ISSUE THREAD

**Issue by scarrmu** [DeltaV-Station/Delta-v#1662]
## Description
The metashield isn't mentioned in the rules for some reason, despite it being enforced as a rule.

**Reproduction**
Opening the rules and seeing it isn't there :3

**Comment by jimmy12or** [comment]
As someone who was just told to review this rule myself, I can agree that this not being in the rules is an issue. I was directed to read it on the Wiki, which not everyone even knows exists.

**Comment by deltanedas** [comment]
mustve been glossed over in the guidebook port https://github.com/DeltaV-Station/Delta-v/pull/1494
