### ISSUE TITLE
Pill/unknown ingredient

### ISSUE THREAD

**Issue by Varenvel** [DeltaV-Station/Delta-v#1681]
## Description
so was playing med and going around gathering maintenance pills , slime broke in one office on Arena station who had 5 pills in container labelled "dump me" , thrilled i went to med and ground them up and 1 ingredient shown up as "unknown ingredient" after i put it into chem master it "disappeared" supposing , but it was just invisible as chem master still said 15u of something , it was just empty. --office is the one with "blue security clothes" i think its office just right of reporter room (below small chem bey/med close to cyro)

**Reproduction**
i guess it should be in code , if not load map several times , grind pills and see if its there

**Screenshots**
 i should make them but was just tired. and replay site for deltaV seams down.

**Additional context**
Round #14681 on map "Arena"

**Comment by IamVelcroboy** [comment]
Some reagent that got removed. I'll look into it
