### ISSUE TITLE
Chief Justice's Spare ID card has no access

### ISSUE THREAD

**Issue by therealDLondon** [DeltaV-Station/Delta-v#1682]
## Description
The chief justice's spare ID found in the locker, plus the ones spawned via "chief justice PDA" and "chief justice ID card" all have no accesses

**Reproduction**
Spawn CJ cabinet
Open it
Get ID
Try it on a door, or the ID Computer

**Screenshots**

https://github.com/user-attachments/assets/0a9af85e-b946-4ecf-ba6e-aa4afc708f8a

**Comment by MilonPL** [comment]
Affects all of the justice ID cards.
