### ISSUE TITLE
Shipyard shuttles need Warp Points

### ISSUE THREAD

**Issue by IamVelcroboy** [DeltaV-Station/Delta-v#1689]
## Description
- ~~Shuttles need to be updated with `directional fans` replacing `tiny fans`~~
- Shipyard shuttles need the "Shuttle" `warp point` added
- ~~See also: [#1179](https://github.com/DeltaV-Station/Delta-v/issues/1179)~~

**Additional context**
Easy money. Just remember to `savegrid` **Do not** `savemap`

**Comment by deltanedas** [comment]
i dont think having screens would matter since they arent station members

**Comment by IamVelcroboy** [comment]
> i dont think having screens would matter since they arent station members

It's just for the evac shuttles. The evac shuttles need them to show the ETD/ETA.

**Comment by IamVelcroboy** [comment]
Just need the Shipyard shuttle warp points now
