### ISSUE TITLE
Cargo Bounty Computer only prints top bounty

### ISSUE THREAD

**Issue by therealDLondon** [DeltaV-Station/Delta-v#1705]
## Description
bounty computer only prints the bounty at the top of the list, no matter which one you try

**Reproduction**
Go to cargo bounty computer
Print any bounty besides the top one
Weep

**Additional context**
Lighthouse Station PR-378 (Round  14792)

**Comment by deltanedas** [comment]
upstream issue with named identifiers running out after big uptime, main servers havent restarted for ages
