### ISSUE TITLE
Felinids cannot Meow

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#1707]
## Description
@meow, no meow. Probably mew and all those other things broken. If you use the emote wheel it works. 

**Reproduction**
plug in your headphones, turn your volume up, and  type @meow as a felinid. 

**Screenshots**
![image](https://github.com/user-attachments/assets/4a2aaa28-80ba-40ba-8b94-657f03ea90f6)

**Additional context**
prior 1  this affects 68% of the playerbase 🧌

**Comment by IamVelcroboy** [comment]
Game is completely busted
