### ISSUE TITLE
Lathe items no longer automatically stack 

### ISSUE THREAD

**Issue by qamodi** [DeltaV-Station/Delta-v#1713]
## Description
e2150ee5f99d1cda7c81c232bcde639825f8d538 introduced a regression where items created in a lathe no longer stack

**Reproduction**
Queue a stackable item  in a lathe/techfab (e.g. Ointment). They will not automatically stack, but appear as single items

**Additional context**
It appears that this regression was introduced in e2150ee5f99d1cda7c81c232bcde639825f8d538.

**Comment by deltanedas** [comment]
upstream issue if real

**Comment by IamVelcroboy** [comment]
> upstream issue if real

Yes, I've seen this talked about upstream as well

**Comment by deltanedas** [comment]
wasnt even caused by my pr :trollface:, it affects all stacking (material ejection) and isnt related to recipes.
