### ISSUE TITLE
MedHud VS Chameleon/Cloaking

### ISSUE THREAD

**Issue by Avalon-Proto** [DeltaV-Station/Delta-v#1725]
## Description
Medical huds reveal people who are invisible or hiding with chameleon 

**Reproduction**
1- Be traitor/Ninja
2- Use cloak/chameleon 
3- Walk near doctor
4- Cry as they call you out
5- Get shot to death

**Screenshots**
https://discord.com/channels/968983104247185448/1114374656443551804/1278003466131996775

**Additional context**
Should probably be fixed so that we don't have issues of doctors being able to see those who are invisible or hidden

**Comment by deltanedas** [comment]
upstream issue im pretty sure we use their medhud now
