### ISSUE TITLE
Female harpies cannot change jumpsuits

### ISSUE THREAD

**Issue by ghost** [DeltaV-Station/Delta-v#1728]
## Description

For some ungodly reason, you can't change whatever jumpsuit you spawn with as a female harpy. It doesn't apply the displacement map to you, and whenever you take it off, you can't put any jumpsuit back on, meaning that you're essentially stuck with the clothes you spawned in with or you're naked.
**Reproduction**

- Open up dev environment / server
- Make female harpy
- Spawn in 
- Take off jumpsuit
- Try to put on another jumpsuit
- Game won't let you do it
- Cry

**Additional context**

It's not very MRP to not have clothes fit you just because you're a female harpy

**Comment by Avalon-Proto** [comment]
I thought harpies could only wear jump skirts?

**Comment by ghost** [comment]
They got a displacement map that allows them to wear normal jumpsuits, when Loadouts came out, and I think this is just a relic of them only being able to wear jumpskirts
