### ISSUE TITLE
Power boost when clicking on low-battery Borg.

### ISSUE THREAD

**Issue by Hitbox4** [DeltaV-Station/Delta-v#1746]
## Description
When I was playing a Borg that was on low battery/out of battery I was able to gain power back briefly (<1second) when I clicked on myself, this allowed me to open doors ect. This could be a feature (?) so apologies if so.

**Reproduction**
Play a Borg, drain the battery until the Borg's lights turn off then left click on the Borg, the lights should return briefly along with movement speed.

**Screenshots**
None.

**Additional context**
I'm not sure what perms I had as an engineering Borg, but I seemed to be able to access places like security using this technique.

**Comment by ghost** [comment]
No idea what language this issue might be in but I'd have to guess it has to do with the interactions between the item and the power comp.

Also might be an upstream issue because Borgs are up there and not maintained down here (well, Security Borg is, but the vast majority of borgs aren't.)

**Comment by deltanedas** [comment]
its an upstream issue since sloth added hardcoded verb for ItemToggle

**Comment by SolStar2** [comment]
I belive this is fixed
