### ISSUE TITLE
micro kitchen freezer isnt a freezer

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#1747]
## Description
- no directional fans so you cant keep cold in
- no freezer for cooling the room
- no freezer locker either

all meat will rot here

**Comment by Radezolid** [comment]
![imagen](https://github.com/user-attachments/assets/d5de9d3c-b3df-46a6-b670-962f8dc21a8c)
There is a freezer there but on normal temp, chef should lower it.
Directionals fans are needed though.

**Comment by deltanedas** [comment]
i say no freezer because its not in the same room so any chef is very likely to miss it

**Comment by IamVelcroboy** [comment]
@Colin-Tel I didn't check for this in last update. But close or fix with next PR.

**Comment by Colin-Tel** [comment]
I didn’t know about it either. I can make a fix for it.
