### ISSUE TITLE
Corpsman does not start w/ lethal mag for the MK58.

### ISSUE THREAD

**Issue by troytroy400** [DeltaV-Station/Delta-v#1749]
## Description
Currently the corpsman does not start with a lethal mag like other security officers. They were never updated after the upstream change that added a lethal mag to all security officers. They should have a MK58 lethal mag in their inventory round start in addition to the rubber bullet magazine loaded into their weapon. 

**Reproduction**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Unkn0wnGh0st333** [comment]
https://github.com/DeltaV-Station/Delta-v/pull/1869
