### ISSUE TITLE
Missing Wing Sleeves

### ISSUE THREAD

**Issue by ghost** [DeltaV-Station/Delta-v#1751]
## Description

A good amount of Harpy suits have wing sleeves. Some do not. This covers them.
**Reproduction**

- Be a harpy Mystagogue, Harpy ERT secoff, or be wearing the carpsuit
- Have no wing sleeves
- Cry

- Be a Harpy CC officer, literally anyone else on the ERT team, a harpy scientist that just reverse engineered a nukie suit, a harpy wearing an NTSRA voidsuit, or Harpy Santa, apparently
- Have your wings be crushed back into human arms.
- Cry harder.
**Screenshots**

![image](https://github.com/user-attachments/assets/b15a681a-df88-4f4e-82bf-f4b9c30bc850) 
![image](https://github.com/user-attachments/assets/361e1aef-7877-4f03-b479-4ad18fbdcdce)

Mystagogue, ERT Sec, Carpsuit doesn't have wing sleeves...
![image](https://github.com/user-attachments/assets/0cb76be2-6b6c-4a6d-9418-563e1d6de2e3)
![image](https://github.com/user-attachments/assets/56729d42-61c3-4879-a515-34e9971e608f)
![image](https://github.com/user-attachments/assets/d3097b31-b0f9-4fa1-abd8-98c4ea1edd12)

Centcom suit, NTSRA voidsuits, ERT Chaplain, ERT medical, ERT Janitor, ERT Engineer, ERT Leader, Santa's hardsuit and both Reverse Engineered hardsuits (SA-122 combat and SA-126 juggernaut) just nukes any semblance of wings, that's cursed.
**Additional context**

It would be nice if all suits had harpy wing covers, this just highlights the ones that don't have them or that I might not have found yet.

**Comment by ghost** [comment]
https://github.com/DeltaV-Station/Delta-v/blob/677bd725f118677b1b2915a33080e45b1c462fc0/Resources/Textures/Clothing/OuterClothing/Hardsuits/rd.rsi/equipped-OUTERCLOTHING-harpy.png Okay, so I've clearly found the Mystagogue one in the files, it just. Won't show up when you equip it, oddly enough. So this might be less of an issue with a lack of sprite but more an issue with how the game accesses the sprites.

**Comment by Timemaster99** [comment]
> https://github.com/DeltaV-Station/Delta-v/blob/677bd725f118677b1b2915a33080e45b1c462fc0/Resources/Textures/Clothing/OuterClothing/Hardsuits/rd.rsi/equipped-OUTERCLOTHING-harpy.png Okay, so I've clearly found the Mystagogue one in the files, it just. Won't show up when you equip it, oddly enough. So this might be less of an issue with a lack of sprite but more an issue with how the game accesses the sprites.

away from my computer right now, but this is likely because the MG hardsuit is missing the harpy wing tag. Add this tag to the MG hardsuit prototype:
```
  - type: Tag
    tags:
    - HidesHarpyWings
```

**Comment by ghost** [comment]
Alright, I'll make a PR shortly that remedies this + sprites the rest of the missing suits.

**Comment by Avalon-Proto** [comment]
Make sure the carp suit wings also apply to the carp pajamas

**Comment by ghost** [comment]
Will do.

**Comment by deltanedas** [comment]
carp suit and carp hardsuit use the same sprite anyway

**Comment by ghost** [comment]
yeah so all it really is is just giving it an outerclothing-harpy sprite so you can be a carp with really large fins i suppose

**Comment by HTMLSystem** [comment]
This issue was fixed by the PR, correct? This could probably be closed now :0

**Comment by ghost** [comment]
Closing because I did it pretty much :3
