### ISSUE TITLE
Deathgasp emote and feign death action shouldn't be available

### ISSUE THREAD

**Issue by perryprog** [DeltaV-Station/Delta-v#1784]
## Description

Part of Delta-V's metagaming guidelines is that simulation of the death rattle (deathgasp) "or other game mechanics" is prohibited. As far as I'm aware, there's no reason we shouldn't hide the deathgasp emote from the emote radial and remove the fake death action from the MobDamageable entity.

**Reproduction**

1. Click the funny skull icon in the emote radial.
2. Be instantly boinked and unappealably banned for use of deathgasp.
<br>

1. Be crit and click feign death because funny.
2. Be instantly boinked and unappealably banned for use of "other game mechanics" to simulate a death rattle. (I assume this is what that clause is referring to.)

**Screenshots**

**Additional context**

I would like to PR a fix for this if possible, assuming I'm not incorrect in my reading of the rules.

**Comment by deltanedas** [comment]
deathrattle has nothing to do with faking death

**Comment by Colin-Tel** [comment]
Nobody has been "unappealably banned" for this.

**Comment by perryprog** [comment]
> deathrattle has nothing to do with faking death

I'm not sure what you mean. Is deathrattle not the noise that plays when you use the `deathgasp` emote or the fake death action while in crit?


> Nobody has been "unappealably banned" for this.

That was just meant as a joke for what would presumably be an incredibly minor rule infraction :)

**Comment by deltanedas** [comment]
deathrattle is a syndicate implant to radio your position on death

**Comment by perryprog** [comment]
Ah, okay, I see that now—I am only referring to the emote/death gasp “noise”, which the rules do refer to as a death rattle:

> Additionally, use of the emote channel to simulate character death rattles or other game mechanics is prohibited.

**Comment by deltanedas** [comment]
thats someone manually writing `*seizes up and falls limb, their eyes dead and lifeless` in chat

**Comment by perryprog** [comment]
Right—currently you can use the emote wheel as a shortcut for this which makes it seem like this is something that is allowed, when that is not the case.

I had assumed the “other game mechanics” bit was referring to the fake death action for when you’re crit which also sends the deathgasp emote/sound, but it sounds like I’m mistaken?

**Comment by ghost** [comment]
I already spoke about fake death with a different maint a while back, and we basically came to the conclusion that you literally can't take it out of this considering you automatically emote it when you die, and in my opinion you shouldn't *not* have the option to emote your fake death. It can make RP sense to emote that, if we had a function for laying down (WHICH IS SOMETHING I NEED TO PORT RAAAAAAAAAAAAHHHHHHHHHHHHHH!!!)

Also yeah, no one has caught an unappealable ban from deathrattle, to my knowledge as someone who's done admin work - all it's resulted on is a tap on the shoulder and saying "hey don't use that because we don't have the mechanics to make it make IC sense." I feel like this part of the rules could be cleared up with a rules rewrite.

**Comment by MilonPL** [comment]
> you literally can't take it out of this considering you automatically emote it when you die, and in my opinion you shouldn't _not_ have the option to emote your fake death

emotes wheel got refactored, we *can* do it now
someone can still type it out manually or bind it but that's an administration issue at this point

**Comment by perryprog** [comment]
Yeah you can take it out of the emote wheel by setting it’s emote category to None or something like that. It might still play the sound if you type it out as I forgot to test that but… eh. I think the more silly thing is having the easily accessible button that is against the rules of to use.

> Also yeah, no one has caught an unappealable ban from deathrattle

I apparently need to work on my bug ticket jokes because it seems my tone didn’t come through at all. Was fully meant as a Funny Joke. 🙃

**Comment by MilonPL** [comment]
Or you can just comment out the chatTrigger.

**Comment by deltanedas** [comment]
the only actual issue here is the emote wheel having deathgasp

**Comment by perryprog** [comment]
👍
And do we care at all about the fake death action that you have while crit? That’s also trivially disable-able.

**Comment by Avalon-Proto** [comment]
> 👍 And do we care at all about the fake death action that you have while crit? That’s also trivially disable-able.

That one has a point to be fair. Try and trick someone into thinking you are dead when you aren't really

**Comment by MilonPL** [comment]
> the only actual issue here is the emote wheel having deathgasp

commenting out the trigger means you can't do "@ deathgasps" or type the whole thing to play the emote but it still works on death
