### ISSUE TITLE
felenids and rodentia in bags can use holo

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#1789]
## Description
basically impossible to see who has it like this

**Comment by Radezolid** [comment]
Not only impossible to see, you can't kill them unless you make them explode in some way (which is not in the usual arsenal of sec.) since you can't shoot them from afar or knife them.

**Comment by deltanedas** [comment]
will be fixed by https://github.com/space-wizards/space-station-14/pull/32068

**Comment by ghost** [comment]
Fixed by the upstream merge Soon ™️ and I didn't even have to triage this. Well done.
