### ISSUE TITLE
Xeno Night Vision can cause invisible Scout WS to be fully visible

### ISSUE THREAD

**Issue by Rainbeon** [DeltaV-Station/Delta-v#1800]
## Description
Xeno Nightvision sometimes does not respect the Scout Weapon Specialist's Thermal Cloak invisibility and displays them as if they are completely 100% visible. This does not require the Xeno to take any unique actions for it to occur, it happens over the course of natural gameplay.

**Reproduction**
I can not currently find any way to manually reproduce this, but it occurs naturally over normal gameplay. May have something to do with latejoins?

**Screenshots**
https://github.com/user-attachments/assets/36464f35-950a-4cef-82d5-1f2ac110ee9f

Only extra context for this occurrence is that I had very recently joined the game, and very recently joined in as Xeno Larva (joined <10 minutes prior), unknown if circumstance is related.

**Comment by deltanedas** [comment]
oh so thats why theyre completely invisible when im xeno but when im ghost i can see them clear as day :trollface:

**Comment by Rainbeon** [comment]
Wrong codebase fml, meant for RMC, disregard

**Comment by deltanedas** [comment]
deltas marine corps :fish::fish::fish:
