### ISSUE TITLE
Links in the rules file are defunct

### ISSUE THREAD

**Issue by Colin-Tel** [DeltaV-Station/Delta-v#1827]
## Description

The link to the privacy policy, as well as the forum are defunct in the rules file.

**Screenshots**

![image](https://github.com/user-attachments/assets/869a2337-1a20-49bb-b350-e394576d5ab0)

**Comment by deltanedas** [comment]
is the privacy policy even stored anywhere now

**Comment by Colin-Tel** [comment]
> is the privacy policy even stored anywhere now

The #information tab on the Discord :trollface: 

![image](https://github.com/user-attachments/assets/163fad0b-ffbe-409a-82b4-a50f0b2f9af2)

**Comment by deltanedas** [comment]
should put it on a wiki protected page then change the link

**Comment by MilonPL** [comment]
config presets should be updated too at some point since infolinks are fucked
