### ISSUE TITLE
vulpkanin clothes do not have species specific sprites in character customization screen

### ISSUE THREAD

**Issue by portfiend** [DeltaV-Station/Delta-v#1831]
## Description
title

**Reproduction**
1. create a vulpkanin character
2. set "mime" priority to high, or another job that comes with a mask as part of the job
3. look at character from side view
4. mask will have the flat "human" sprite, and not the vulpkanin-specific snouted sprite

**Screenshots**
![Screenshot_203](https://github.com/user-attachments/assets/9a8480bb-b6c0-41df-a88a-2d0e0b2624cf)

**Additional context**
this will be an easy fix, just apply this to `MobVulpkaninDummy` or some shiut

```
  - type: Inventory
    speciesId: vulpkanin
```

**Comment by Avalon-Proto** [comment]
I shall mention this also happens with lizards and their feet unique mask sprites. IE clown and so on

**Comment by portfiend** [comment]
> I shall mention this also happens with lizards and their unique mask sprites. IE clown and so on

actually i fixed this upstream a few months ago
