### ISSUE TITLE
Banana Cream Pies don't drop Pie Tins after being Thrown

### ISSUE THREAD

**Issue by masterofnursing** [DeltaV-Station/Delta-v#1843]
## Description

Banana cream pie is thrown, hits a target, but then no pie tin is placed at their feet.

**Reproduction**

Lovingly craft a banana cream pie
Giggle mischievously
Splat a silly victim
Weep as the pie tin does not appear at their feet, and you cannot reload at the microwave anymore.

**Comment by ghost** [comment]
To my knowledge this might be an easy yaml fix if we look in the code for other pies and what they drop. If you wanna learn yaml / item states or whatever, try looking for it!
