### ISSUE TITLE
Evac shuttles missing comp for screens to show ETA/ETD

### ISSUE THREAD

**Issue by IamVelcroboy** [DeltaV-Station/Delta-v#1849]
## Description

- [x] NTES_Vertex
- [x] NTES_UCLB

Needs 

```
    - type: DeviceNetwork
      configurators: []
      deviceLists: []
      transmitFrequencyId: ShuttleTimer
```

**Additional context**
Easy peasy yaml copy/paste

**Comment by FryOfDestiny** [comment]
I added a pull request, it's my first time so not sure if I did it right.

**Comment by IamVelcroboy** [comment]
> I added a pull request, it's my first time so not sure if I did it right.

Looks good. Thank you

**Comment by therealDLondon** [comment]
I know a PR was merged for the Titan but I believe the Vertex and Fishbowl share the same issue

**Comment by IamVelcroboy** [comment]
> I know a PR was merged for the Titan but I believe the Vertex and Fishbowl share the same issue

Looks like the Vertex, yes. Fishbowl is good to go

**Comment by IamVelcroboy** [comment]
Looks like Uncle Charlie's Luxury Boat needs it too. Which is weird, should have been fixed in first pass 🤔
