### ISSUE TITLE
Shoko pumps missing LV 

### ISSUE THREAD

**Issue by MilonPL** [DeltaV-Station/Delta-v#1853]
## Description

PR [#28995](https://github.com/space-wizards/space-station-14/pull/28995) got merged upstream meaning we will probably get it here soon. All pumps now require power, but Shoko is missing LV in two places, see media. I went over every other map and it seems like this is the only one with this issue.

**Screenshots**

TEG cold loop
![image](https://github.com/user-attachments/assets/def0e27b-5ecb-4d8f-b385-58ce3fc032ff)

Recycler radiators
![image](https://github.com/user-attachments/assets/f1394d7d-0411-483e-b18d-e635d80c507f)

**Comment by deltanedas** [comment]
recycler ones have lv in the grilles i think

**Comment by MilonPL** [comment]
> recycler ones have lv in the grilles i think

the old map render shows them as having lv but apparently it was changed with the last shoko patch and also we're back to 2 radiators instead of 4 for whatever reason
