### ISSUE TITLE
Rodentia doesn't get thirsty

### ISSUE THREAD

**Issue by TheYaket** [DeltaV-Station/Delta-v#1856]
## Description

Rodentia doesn't really get thirsty/It doesn't show (Don't really know how to check it)

**Reproduction**

Just need to play for some time in a round as Rodentia without drinking

**Additional context**

The issue was here since Rodentia got added.

**Comment by Colin-Tel** [comment]
![image](https://github.com/user-attachments/assets/16fde74c-1bbe-43e9-b4e9-d93f865f8a64)
no thirst component hee hee
