### ISSUE TITLE
barefoot felinids are not silent when walking

### ISSUE THREAD

**Issue by Proxysseia** [DeltaV-Station/Delta-v#1865]
## Description
Felinids play walking sounds when barefoot, conflicts with guidebook entry of upside of felinids being silent while barefoot. 

**Reproduction**
spawn as a felinid. take off shoes, press w a s or d key as per preference :)

**Comment by MilonPL** [comment]
shitter NoShoesSilentFootstepsComponent broke because steptrigger changes will try to fix sometime
edit: nvm stepstrigger unrelated but still
