### ISSUE TITLE
Song has unknown artist and unknown title

### ISSUE THREAD

**Issue by beck-thompson** [DeltaV-Station/Delta-v#1873]
## Description

Song goes like this:
(Background): buwuhhhh bwuhhhh bwuhh
(Foreground): duh duh duh duh duh duh duh

**Screenshots**

![Screenshot 2024-09-20 154930](https://github.com/user-attachments/assets/b1deb9aa-07c5-4502-bb12-db82401cccd1)

**Comment by therealDLondon** [comment]
The songs are "The Station" and "Get It Done" both by "A-Guy"
The attributions are messed up, lmao.

**Comment by beck-thompson** [comment]
Glad my amazing musical translation helped you determine the songs 🫡

**Comment by therealDLondon** [comment]
> Glad my amazing musical translation helped you determine the songs 🫡

They were fantastic, but im the one who added them in the first place so-

**Comment by ghost** [comment]
Good first issue because all it is is proper attribution or at least fixing of it in the attributions yaml.
