### ISSUE TITLE
Chapel sign is green, not purple

### ISSUE THREAD

**Issue by therealDLondon** [DeltaV-Station/Delta-v#1909]
## Description
Upstream change, chapel is service over there, not epi

**Reproduction**
Look at a chapel sign and cry

**Screenshots**
![image](https://github.com/user-attachments/assets/e316ae33-904f-4889-a0a0-0f9d45e6b3d1)

**Additional context**
Good first issue, just a simple sprite change

**Comment by IamVelcroboy** [comment]
Make it less Christian too

**Comment by Lyndomen** [comment]
![chapel](https://github.com/user-attachments/assets/5b91dd00-4a55-495c-a491-1209338d538f)
if  its good enough, anyone can feel free to PR it. If nobody grabs it ill do it in a few days
