### ISSUE TITLE
The mini medic vending machines on Arena are operable upside down, which means the last one is inaccessible in MedBay

### ISSUE THREAD

**Issue by TheYaket** [DeltaV-Station/Delta-v#1919]
## Description

As the title says, these vending machines can be used from the UP position, not from DOWN. They are on the upper walls of the rooms, which means the last one is inaccessible 

**Reproduction**

Go to MedBay with medical access, go to each one from the bottom

**Screenshots**

![image](https://github.com/user-attachments/assets/ef885fa2-d33a-4018-8e83-4df280c4d917)

**Additional context**

**Comment by IamVelcroboy** [comment]
Looks to me like they are all oriented the correct direction 
![Uploading image.png…]()
somebody might have broke the directional stuff again 🤷‍♂️

**Comment by TheYaket** [comment]
Yeah when I played today it was fine, forgot to write about it, really weird.

**Comment by Colin-Tel** [comment]
the curse of the wallmounted nanomed strikes again!!
