### ISSUE TITLE
Theobromine poisons moths

### ISSUE THREAD

**Issue by boogiebogus** [DeltaV-Station/Delta-v#1926]
## Description
Theobromine poisons moths now, which I'm pretty sure is not intended.

**Reproduction**
1. Be moff
2. Drink something with theobromine in it (or just inject it)
3. Cry

**Screenshots**
![image](https://github.com/user-attachments/assets/017be576-f95c-4fdc-8677-8fc77ac42c86)

**Additional context**
N/A

**Comment by MilonPL** [comment]
Theobromine was always poisonous to moths, but up until recently you needed at least I believe 1u in bloodstream (which you'd realistically never get from drinks, as they add 0.05u). That was changed upstream, so now any amount will poison moths, lizards, rodentia, arachnids, harpies and felinids.
