### ISSUE TITLE
Some maps still have improper physics settings

### ISSUE THREAD

**Issue by IamVelcroboy** [DeltaV-Station/Delta-v#1931]
## Description
`angularDamping`/`linearDamping` not set to `0.05`
- [x] Arena
- [x] Edge
- [x] Hammurabi
- [x] The Hive
- [ ] Pebble
- [x] Tortuga

Has extra `shuttle` comp
- [x] Arena
- [x] Edge
- [x] Hammurabi
- [x] The Hive
- [ ] Pebble
- [x] Shoukou
- [x] Tortuga

**Comment by IamVelcroboy** [comment]
@DeltaV-Station/maptainers

**Comment by deltanedas** [comment]
glacier specifically doesnt use anchor since its built into a mountain or something

**Comment by IamVelcroboy** [comment]
> glacier specifically doesnt use anchor since its built into a mountain or something

That makes sense. Does that explain the second physics comp too? or..?

**Comment by deltanedas** [comment]
i think the 2 components are for the map and grid, not sure if map inertia does anything though

**Comment by IamVelcroboy** [comment]
> i think the 2 components are for the map and grid, not sure if map inertia does anything though

So, should I remove Glacier from this?

**Comment by deltanedas** [comment]
yeah probably, having the map inertia does no harm
