### ISSUE TITLE
Prisoner Jumpskirt loses stripes in DV server

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#1952]
## Description
When you are a prisoner, the prisoner jumpskirt no longer has stripes. This is only applicable on the DV server, but a debug mode local environment has the stripes working. 

**Reproduction**
Spawn in as a prisoner on horizon :godo:

**Screenshots**
Horizon Pic (spawn in atmos for free plasma)
![image](https://github.com/user-attachments/assets/99fc5825-ba9d-43ff-8f0d-9f4f5f7278a8)

Dev Env pic
![image](https://github.com/user-attachments/assets/6c2c45ab-c9f9-4d0c-9170-a195b6f5101d)

**Additional context**
wtf

**Comment by Lyndomen** [comment]
Vulps work? 
![image](https://github.com/user-attachments/assets/5ffcf826-82f3-4f34-9f54-f0e1de2deb4b)

**Comment by portfiend** [comment]
Upstream issue, it has to do with species displacement maps: space-wizards/space-station-14#30565 Actually wait it JUST got fixed like yesterday that's awesome

**Comment by Radezolid** [comment]
I'm seeing stripes on the prisoners now, post upstream merge, including https://github.com/space-wizards/space-station-14/issues/30565.
