### ISSUE TITLE
Uplink Implanter doesnt get discounts

### ISSUE THREAD

**Issue by Proxysseia** [DeltaV-Station/Delta-v#1967]
## Description
Uplink Implanter doesnt get discounts, both the tab and the actual discounts.

**Reproduction**
Obtain and use antag token.
Obtain and use uplink implanter.
Use the shopping website of your choice to get the best deals possible (in your PDA)
Compare to Implanter prices and weep.

**Screenshots**
Someone with an actual dev enviroment go help me out pretty please thanks.

**Comment by Radezolid** [comment]
I think this would be a upstream issue but it's a okay one?
IMO you're sacrificing the discounts + 2 TC for a uplink implanted which you can use in prison or if someone takes away the PDA.

**Comment by deltanedas** [comment]
its intentional i believe to avoid cycling discounts by buying a bunch of uplink implants and checking each one
