### ISSUE TITLE
Shoko freezer starts unpressurized and with no air

### ISSUE THREAD

**Issue by HTMLSystem** [DeltaV-Station/Delta-v#1978]
## Description

The kitchen freezer has a passive vent in it and a passive gate connecting it to distro. At round start the freezer has little-no pressure and no air in it. It doesn't fix itself until the passive gate and passive vent is replaced with a regular pipe and regular air vent. 
**Reproduction**

1. Load up shoko map
2. Walk into the freezer
3. Uh oh! no air or pressure for the entire shift until you fix it!
**Screenshots**

![image](https://github.com/user-attachments/assets/ba3b3b87-93d7-4153-a361-47ca71c01d8c)

**Additional context**

I haven't gotten to look at it in detail but this is just my experience with it. Both times I've fixed it myself with a regular pipe and regular air vent.

**Comment by deltanedas** [comment]
if you replace the passive gate with a pipe you will cool distro which will make atmos send hitmen after you
the gate should be replaced with a gas pump to cope with distro that isnt 1 atm

**Comment by HTMLSystem** [comment]
Hmmm, I'll try and test it out later today to see how it works out.

**Comment by Unkn0wnGh0st333** [comment]
I'll replace the vent, should fix it. My baaaad

**Comment by Unkn0wnGh0st333** [comment]
This should be fixed
