### ISSUE TITLE
Tiles/airlocks/walls resprite issues

### ISSUE THREAD

**Issue by MilonPL** [DeltaV-Station/Delta-v#1989]
## Description

Hydroponics (https://github.com/space-wizards/space-station-14/pull/32575) and chemistry (https://github.com/space-wizards/space-station-14/pull/30666) airlocks both need respriting, something should be done about the riveted walls as well so they don't stand out and collide with the art style so much. 

Since Noctis left the team and we do not have anyone willing to maintain the sprites, now is the time to consider reverting the resprite, as we're going to run into more and more issues with it. That's why I'm marking this issue as **urgent**, in hope someone picks it up, because I really like the sprites.

**Comment by Unkn0wnGh0st333** [comment]
I'll look at em today, completely forgot this needed to be done. If they are outside my skill level I'll let ya know :blunt:
