### ISSUE TITLE
Kebabs not working

### ISSUE THREAD

**Issue by UVEsteban** [DeltaV-Station/Delta-v#1990]
## Description
No way to make a kebab

**Reproduction**
Skewer+ingredient (separated) -> microwave = ingredient cooks but outside the skewer
Skewer on ingredient -> nothing happens
Ingredient on Skewer -> nothing happens
Hit the ingredient with the skewer -> nothing happens
Hit the Skewer with the Ingredient -> nothing happens
**Screenshots**
![image](https://github.com/user-attachments/assets/0fa7a875-226d-4d68-b3d0-cef9ff8c9f13)

**Comment by deltanedas** [comment]
WOMM
![01:27:09](https://github.com/user-attachments/assets/0e7b3050-513f-430d-9f3b-8aec33ffdee0)

microwave isnt involved with food sequence, all that matters is that the ingredient is allowed to go on a type of sequence (like mouse or chili peppers, pineapple doesnt have it)

**Comment by Avalon-Proto** [comment]
> WOMM ![01:27:09](https://private-user-images.githubusercontent.com/39013340/375373825-0e7b3050-513f-430d-9f3b-8aec33ffdee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NjM2NjgsIm5iZiI6MTcyODU2MzM2OCwicGF0aCI6Ii8zOTAxMzM0MC8zNzUzNzM4MjUtMGU3YjMwNTAtNTEzZi00MzBkLTlmM2ItOGFlYzMzZmZkZWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDEyMjkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTczOWUzOGVkOWY4MDRkZGQ5ZDEwZTlmNTY5MmQyOTQ1Mjk5ODIwYmUwNTc0NTIxODFiOTAyYWMyMjJkMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dB_RYuRCghavkpU3IJd9u_e7E76M-eeMGGeg02XXJrk)
> 
> microwave isnt involved with food sequence, all that matters is that the ingredient is allowed to go on a type of sequence (like mouse or chili peppers, pineapple doesnt have it)

Shouldn't Cutlets and pineapple have it though? Those are both things you would normally put on a kebab

**Comment by deltanedas** [comment]
wyci and an upstream issue, a lot of foods had food sequence removed in a culling

**Comment by UVEsteban** [comment]
So is fixed? sorry this is my first issue here and since now the issue is closed... that was all?

**Comment by UVEsteban** [comment]
> WOMM ![01:27:09](https://private-user-images.githubusercontent.com/39013340/375373825-0e7b3050-513f-430d-9f3b-8aec33ffdee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MDAxNjcsIm5iZiI6MTcyODU5OTg2NywicGF0aCI6Ii8zOTAxMzM0MC8zNzUzNzM4MjUtMGU3YjMwNTAtNTEzZi00MzBkLTlmM2ItOGFlYzMzZmZkZWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDIyMzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYWU0YjhlYTRhZDI4NjA0Nzk0NGNkYzE4OGEwMjc3YTY0NmRmNWU1M2Y4ZTQwZjAyMDM1ZTk0NDNlOWU5MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EJW6fU-TDBuQ1IrL_b3LBRc9b0CrS7oewwcRVShz0pQ)
> 
> microwave isnt involved with food sequence, all that matters is that the ingredient is allowed to go on a type of sequence (like mouse or chili peppers, pineapple doesnt have it)

then, the wiki is not right, right? does anyone have the updated list of ingredients for kebabs?

**Comment by Radezolid** [comment]
> So is fixed? sorry this is my first issue here and since now the issue is closed... that was all?

Basically what they mean it that the food that you meant to use haven't been designated as being able to be used but since the problem comes from upstream (main repository of SS14) the issue should be made there but [this issue](https://github.com/space-wizards/space-station-14/issues/31083) exists already and it was marked as closed too. Maybe try and open another and see if someone is up for it? Since it was never restored. 

> then, the wiki is not right, right? does anyone have the updated list of ingredients for kebabs?

You're right, the wiki needs to be updated. And no idea on a updated list, sorry.
