### ISSUE TITLE
Weird behaviour on hammurabi's anchor LV wires.

### ISSUE THREAD

**Issue by Radezolid** [DeltaV-Station/Delta-v#1991]
## Description

Weird behavior on LV wires on hammurabi's LV wires makes the anchor unpowered.

**Reproduction**

See the video below.

**Screenshots**

https://github.com/user-attachments/assets/71436cb3-471d-465a-8185-15e7c5a290f7

**Additional context**

The floor was made plating and window + airlock removed by me for a more clear video. The wiring was as how the station loads.

**Comment by IamVelcroboy** [comment]
😲
