### ISSUE TITLE
Unable to drag and drop hotbar items

### ISSUE THREAD

**Issue by michaelsshaw** [DeltaV-Station/Delta-v#1993]
## Description
The "hotbar" as I have described it, is the action menu on the left (or top) of the screen. Its actions, such as harm, scream, PDA light, etc... were previously "drag-and-drop"-able and now they are not. I believe this is a regression, as adding actions back after right-clicking to remove is seemingly impossible

**Comment by Avalon-Proto** [comment]
It's an upstream issue, as soon as the upstream merge PR goes through from Deltanedas should be fixed
