### ISSUE TITLE
Add Code of Conduct to the Repository

### ISSUE THREAD

**Issue by Brijeshthummar02** [DeltaV-Station/Delta-v#2014]
Explanation: We want to improve the inclusiveness and community standards of our business by including a code of conduct. This manual will help create a comfortable and welcoming environment for both providers and users.

Suggested Resources:

• A brief introduction to the purpose of the Code of Conduct
• A Guide to Respectful Communication
• expectations of behavior in the community
• Misconduct reporting procedures

Steps in reproduction:

• Create a new file named CODE_OF_CONDUCT.md in the root directory of the repository.
• Include the items listed above, as well as any additional items you deem necessary.

Expected Results:

A comprehensive code of conduct that aligns with the values ​​of our profession and is easily referenced by the entire community.

Labels: good first issue, documentation

**Comment by deltanedas** [comment]
chatgpt cant apply labels, its over
