### ISSUE TITLE
Add CONTRIBUTING.md file to the repository

### ISSUE THREAD

**Issue by Brijeshthummar02** [DeltaV-Station/Delta-v#2015]
Issue Description: Would it be possible to add a CONTRIBUTING.md file to the repository? Having this file in place would provide clear guidelines for new contributors on how to contribute effectively to the project, including steps for setting up the development environment, coding standards, and the process for submitting pull requests. This will help streamline the contribution process and encourage more participation.

**Comment by deltanedas** [comment]
law 2 state your prompt
