### ISSUE TITLE
Crusher Glaive can swing while wielded during pacifism.

### ISSUE THREAD

**Issue by freeskrub** [DeltaV-Station/Delta-v#2042]
## Description
So, the crusher glaive can attack while wielded even if pacified. No clue why! But what this CAN do is let you attack objects during end of round. 
This, of course, lead to me getting a 2 hour ban for end of round grief after letting someone drag me into an electrified grille repeatedly, thereby proving a hypothetical manner of killing people during EOR. 

**Reproduction**
Prerequisite: Have the Pacification (either via thief, trait, or by EOR pacifism) effect.
Step 1: Wield a crusher glaive (or, presumably, a normal crusher)
Step 2: Attack. At all.  You can wideswing with the glaive while wielded in this state, since you can't shoot it in this state.
Step 3: Swing at a window with an electrified grille underneath and throw yourself into it, to provide a hypothetical manner of killing someone during EOR. You cannot deal damage to players with it, but you can deal damage to terrain!
Or just space the place and kill everyone that works too.

**Screenshots**
Yeah you know that 2 hour ban? Can't exactly get a screenshot when i've been hit over the head with a steel folding chair.

**Additional context**
Breaking shit during EOR is a bannable offense by delta, and you shouldn't be able to do anything remotely harmful DURING EOR with pacifism, but this directly bypasses that fact. It's like a 2 hour ban but still.

**Comment by deltanedas** [comment]
your ban is unrelated to the glaive, which can swing normally if you manage the cooldowns right
pacifists not being able to break structures would be terrible for thief, this would need an end of round specifics solution
