### ISSUE TITLE
Infection anomalies aren't producing glimmer

### ISSUE THREAD

**Issue by Radezolid** [DeltaV-Station/Delta-v#2045]
## Description
Infection anomalies are not producing glimmer, making them free points for no consequence. Even making them go critical doesn't generate glimmer.

**Reproduction**

1. Spawn any infection anomaly.
2. Infect something with it.
3. Link to the vessel.
4. Enjoy the free points.

**Screenshots**

https://github.com/user-attachments/assets/b7f05796-6d6c-49ea-b06d-7563a8a81f15

**Additional context**
None.

**Comment by MilonPL** [comment]
[anomaly_injectors.yml](https://github.com/DeltaV-Station/Delta-v/blob/d50df0e13fac5ced1f8424b753ea04bc6c305630/Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomaly_injectors.yml) need to inject GlimmerSource, see https://github.com/DeltaV-Station/Delta-v/blob/d50df0e13fac5ced1f8424b753ea04bc6c305630/Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomalies.yml#L62-L63
