### ISSUE TITLE
Station Anchor room in Arena missing a tile, starts and stays spaced

### ISSUE THREAD

**Issue by HTMLSystem** [DeltaV-Station/Delta-v#2122]
## Description

The station anchor room in Arena starts spaced. There's a missing tile under the center of the station anchor. Additionally, the room stays PERMANENTLY spaced even after to fix it, leading to the entire engi department showing up red on the atmos console. 
**Reproduction**

1. Load up the map Arena
2. Start round
3. Go to Station Anchor room
4. It stays space the entire round
**Screenshots**

N/A
**Additional context**

I learned this on round #16658 where a lot of other funky atmos shit was happening.

**Comment by Monotheonist** [comment]
@IamVelcroboy Arena's your map, so I'm pulling you into this.
