### ISSUE TITLE
roboticist should be in engineering 

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#2135]
## Description
Engineers build stuff and need more work. Borgs can be built and maintained by them, they are often better equipped to do so. This also tightens the gap between engi and salv if engi can build a shuttle for salv in return for mats or whatever

Also epi is evil and doesn't need bots

**Reproduction**
Fuck if I know, this isn't an issue

**Screenshots**
I am coping

**Additional context**

**Comment by IamVelcroboy** [comment]
Jayzus, I've moved robotics so many damn times
