### ISSUE TITLE
make nukies MRP 

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#2136]
## Description
Murderbone antags with only people pretending to get along at best, everyone knowing it will come to a fight eventually. Often pretty NRP TDM fun, but not MRP 

**Reproduction**
play a round with red guys

**Screenshots**

**Additional context**

**Comment by Monotheonist** [comment]
Here's my take: this has been a problem to anyone who has played the game for a long time. It gets repetitive: some people like the adrenaline from the gamemode. Other people like to roleplay it out with things. 
In a team of nuclear operatives, the want to talk to the crew and the want to just murder often clash -
 I've experienced it myself with a guy coming in the cargo shutle when we'd stormed the place on a successful nukie round, and there was some RP potential, and the commander just minibombed the guy who said they didn't want trouble. Cruel negation of possible RP, but I guess that's how it is.
Given that Delta-V is a fork attached to an MRP server, it clashes with the very nature of roleplay when things like that happen, and the war declaration seems to have made the problem of non-RP full combat gung-ho nukies worse. 
Someone should probably do something about that if it's an issue. It's an entire discussion. :P
