### ISSUE TITLE
issue page kinda shit

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#2137]
## Description
Apparently for discussion but not very clear. Links go to ss14 discord not ours. Add a new category for discussion I guess IDK 

**Reproduction**
Engage copium drive, press new issue, click buttons in confusion

**Screenshots**

![Screenshot_20241106-221818](https://github.com/user-attachments/assets/d5cb3728-1780-47f1-ae3d-782f158734a2)

**Additional context**

**Comment by Monotheonist** [comment]
> Add a new category for discussion I guess IDK

Lyndo, that exists on the desktop version. They shouldn't have pointed you to the issues page, but I guess that's an issue, so like. Hmm.
![image](https://github.com/user-attachments/assets/29f0af60-c4ee-4193-a2ac-a80314ee4b0a)
(circled for emphasis)

Should be under those three dots on the mobile version.

**Comment by MilonPL** [comment]
No one ever uses discussions, not sure why we have it enabled.

**Comment by Monotheonist** [comment]
Well maybe you should start pointing people there so it gets used, I dunno. 🤷
