### ISSUE TITLE
I have repo access

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#2139]
## Description
I have quit and I should not longer have any repo access

**Reproduction**
Quit, close all the PRs before the feds catch you, earn repo ban

**Screenshots**
Woe, no screenshot- trust me 

**Additional context**
no issue no problem

**Comment by Lyndomen** [comment]
I cant fix this with webedit

**Comment by MilonPL** [comment]
https://github.com/settings/organizations
![image](https://github.com/user-attachments/assets/000bba72-c504-46ae-8911-079b7bc72d9a)
