### ISSUE TITLE
Can't dock right on shoko.

### ISSUE THREAD

**Issue by SunnyGaming3710** [DeltaV-Station/Delta-v#2146]
## Description
On Shoko, you can't dock the cargo shuttle properly. You can scooch to get one door, but you cannot get both.

**Screenshots**
![{460720DF-7166-4CF2-853D-B7CE8DA4BF5B}](https://github.com/user-attachments/assets/a2f6d6c1-e04e-4453-9fbb-3f4049d602f5)

**Additional context**
There's this little hook add-on near EVA that's probably meant to shield it from meteors and all that, EXCEPT... it's also blocking the cargo shuttle from being able to dock right. 
![{AF2B3AF5-BDD9-428C-9F62-98089ABA52CC}](https://github.com/user-attachments/assets/73aa43e3-9d25-4a74-8913-3bf7b1fd9a60)

**Comment by Unkn0wnGh0st333** [comment]
OH GOD

**Comment by deltanedas** [comment]
doesnt even help against meteors :trollface:
