### ISSUE TITLE
metem machine sucks

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#2153]
## Description
Dsymorphia machine supposed to give consequences to people dying, but leading consequences is /ghost 

**Reproduction**
Die, forget to tick uncloneable, come out as Oni, /ghost

**Screenshots**

**Additional context**

**Comment by Lyndomen** [comment]
![Screenshot_20241108-073934](https://github.com/user-attachments/assets/3ab8cee4-e946-4a6f-81ef-ae8a48d9e988)
Wow so unbiased

**Comment by MilonPL** [comment]
i say we nuke it

**Comment by Lyndomen** [comment]
Maybe give cloning as t3 medical to compensate

**Comment by deltanedas** [comment]
> Maybe give cloning as t3 medical to compensate

upstream had that already then axed it since it just ends up with sec threatening sci to get cloning or else

**Comment by Lyndomen** [comment]
God forbid epi have a use
