### ISSUE TITLE
centcom encourages eorg

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#2165]
## Description
Big room, lots of people, lots of chaos. 

**Reproduction**
Play end of round on apo, people get crazy 

**Screenshots**

**Additional context**
I forgot that I hate a date planned tonight but am 90% done making a quick fix to the map. Don't ninja this away from me.

**Comment by Radezolid** [comment]
Duplicate https://github.com/DeltaV-Station/Delta-v/issues/1685

**Comment by Lyndomen** [comment]
God damn it I even commented on it
