### ISSUE TITLE
Can use items your pulling

### ISSUE THREAD

**Issue by FryOfDestiny** [DeltaV-Station/Delta-v#2168]
## Description
When dragging an item like a spray bottle or mop you are able to click to use them as if they were in your hand.

**Reproduction**
Drag a filled spray bottle then click. 

**Additional context**
Might be an upstream issue, but I found it while playing here so I submitted it here.

**Comment by deltanedas** [comment]
yeah its an upstream issue, even lets you use dead spiders for AA

**Comment by FryOfDestiny** [comment]
Same issue as spider jaws so I closed jt
