### ISSUE TITLE
Plutonium Core does not fit in the Nuke Core Container

### ISSUE THREAD

**Issue by Samsterious** [DeltaV-Station/Delta-v#2173]
## Description
The Nuke Core Container is provided by the Core Extraction Kit, presumably to hold the very radioactive Plutonium Core that is to be extracted. However, the core cannot, in fact, be placed inside, as it does not fit!

**Reproduction**
1. Roll Syndie
2. Purchase a Core Extraction Kit from the Uplink
3. Hack the Nuclear Fission Explosive
4. Attempt to place the Plutonium Core into the Nuke Core Container
5. Observe the popup

**Screenshots**
![image](https://github.com/user-attachments/assets/ba4be3ef-383d-44ee-8acc-fa522672b55c)
![image](https://github.com/user-attachments/assets/d3c0a3c1-9f80-4c02-838f-ba5ff4cba010)

**Additional context**
Presumably irradiating themselves to death is counter to a Syndie's odds of survival and also success!

**Comment by Radezolid** [comment]
The core fits in the container, you gotta open it first.

https://github.com/user-attachments/assets/f59d75af-a495-4b35-86fa-c4030c4b4c3a

**Comment by deltanedas** [comment]
popup was recently fixed and will have to be updated, previously it just said nothing

**Comment by Samsterious** [comment]
Tell me I never play Syndie without telling me I never play Syndie, pft.

**Comment by deltanedas** [comment]
popup is still wrong

**Comment by Kr8art** [comment]
Fixed popup in https://github.com/DeltaV-Station/Delta-v/pull/2309!
