### ISSUE TITLE
Someone got 10 billion objectives 

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#2203]
## Description
I just saw this in discord, looks like a reinforcement 

**Reproduction**

**Screenshots**

![image-62](https://github.com/user-attachments/assets/488946bb-9451-43c2-a4e7-609d96b7ee6f)

**Additional context**

**Comment by Lyndomen** [comment]
Dupe I woke up confused

**Comment by MilonPL** [comment]
??????

**Comment by Lyndomen** [comment]
> ??????

I woke up and was like damn I should submit that issue
