### ISSUE TITLE
feat: SusVend restock box [good first contribution]

### ISSUE THREAD

**Issue by DisposableCrewmember42** [DeltaV-Station/Delta-v#2222]
> Another suggestion, one or two of these would probably be a good addition to the perma SusVend

> Speaking of that machine, it needs a restock or something. Currently doesn't have one and it'd be nice to be able to restock it so the Perma players have somewhat reliable food besides what they make

_Originally posted by @Avalon-Proto in https://github.com/DeltaV-Station/Delta-v/issues/2210#issuecomment-2481408600_

---

A restock box orderable by logistics should be added for the Sustenance Vendor.

If nobody does this in a few days, I'll probably do it. would just be a good starting point for someone who wants to contribute.

**Comment by Kr8art** [comment]
Addressed in PR https://github.com/DeltaV-Station/Delta-v/pull/2307!
