### ISSUE TITLE
Shoko medical can be opened from the outside

### ISSUE THREAD

**Issue by Kr8art** [DeltaV-Station/Delta-v#2238]
## Description
The main medical area on Shoko can be accessed from the outside by pressing the emergency button on the other side through the glass wall.

**Reproduction**
- Walk up to the glass wall
- Click the button
- Watch the door open
- Enter without access (politely)

**Screenshots**
Short clip:
https://github.com/user-attachments/assets/1ef2a6d8-afe6-479a-92cc-fcc20a8ba764

**Comment by Unkn0wnGh0st333** [comment]
I see, it will be fixed next map update. The reason it's broken is because the button isn't a directional button letting it be pressed from all sides. Pretty simple fix
