### ISSUE TITLE
Chronic Pain- Everyone knows

### ISSUE THREAD

**Issue by Avalon-Proto** [DeltaV-Station/Delta-v#2247]
## Description
The chronic pain popup messages can be seen by everyone near the person who has it

**Reproduction**
1) Urist A has the trait, Urist B does not
2) Urist A has the popup stating their pain has started
3) Urist B can see the popup
4) Confusion ensues

**Additional context**
That's it, no idea how to fix it, just saw it earlier

**Comment by MilonPL** [comment]
WHOOPSIE

**Comment by IAmNotGray** [comment]
Hey, just call it global pain. Everyone feels it at the same time!

**Comment by boogiebogus** [comment]
> Hey, just call it global pain. Everyone feels it at the same time!

new glimmer event real???
