### ISSUE TITLE
Arena shuttle is always in the wrong spot

### ISSUE THREAD

**Issue by Stop-Signs** [DeltaV-Station/Delta-v#2281]
## Description
arena shuttle always docks south instead of east, which causes evac to take forever.

**Reproduction**
go to arena and call evac

**Screenshots**

**Additional context**

**Comment by IamVelcroboy** [comment]
The south dock *is* the intended evac dock

**Comment by Stop-Signs** [comment]
> The south dock _is_ the intended evac dock

the game registers it as the wrong spot and delays evac to 400 seconds instead of 180

**Comment by IamVelcroboy** [comment]
> the game registers it as the wrong spot and delays evac to 400 seconds instead of 180

Hmm, OK. Guess I'll have to look into what that's about then.

**Comment by deltanedas** [comment]
fun fact if you block east docks it will dock at the right place by force

**Comment by IamVelcroboy** [comment]
OK, I figured it out. Fix will be bundled with the AI update
