### ISSUE TITLE
Silvia can no longer strap themselves or other players to beds/chairs/cryobeds

### ISSUE THREAD

**Issue by GrotsnikMD** [DeltaV-Station/Delta-v#2348]
## Description
Silvia can no longer strap themselves or other players to beds/chairs/cryobeds.
There is still a do-over meter to plays after attempting to do but nothing else happens afterwards as expected.

**Reproduction**
Left-click hold on yourself or other entities like player characters.
Drag to a bed or chair or cryo-bed.
A do-over meter appears as if something is about to happen.
Nothing happens.

**Additional context**
This used to work a month ago and has not worked for at least several days. Unsure exactly when it broke beyond that.

**Comment by Unkn0wnGh0st333** [comment]
Silvia should not be able to strap other players or themselves to medical beds.

They are a playable PET, they are not meant to be an extension of the medical staff besides the "emergency omnizine bite" which is utterly overused by the playerbase and gets in the way of doctors VERY often who are trying to heal patients.

**Comment by deltanedas** [comment]
snake does not have hands
