### ISSUE TITLE
Chameleon projector allows non-english speaking animals to speak

### ISSUE THREAD

**Issue by Everturning** [DeltaV-Station/Delta-v#2370]
## Description
In a round I was thief and had to go SSD. There was a scugcat who had just joined and had not been given cognizine yet. After showing the scug how to use the projector, I spoke to it and it spoke back. We were then very confused in LOOC and it was very funny but also a bug.

**Reproduction**
>be scug, or smth that doesn't speak english
>have hands
>take chameleon projector and use it on object
>since you are no longer the funny stormrealm creature (I think it's this bc it uses polymorph) you can speak language
>budget babel book

**Comment by therealDLondon** [comment]
Are you sure this is the right repo?
We dont have scugs

**Comment by Everturning** [comment]
Huh, yeah wrong repo
