### ISSUE TITLE
diona are not slow

### ISSUE THREAD

**Issue by Lyndomen** [DeltaV-Station/Delta-v#2411]
## Description
title
https://github.com/DeltaV-Station/Delta-v/pull/2204

**Reproduction**
be diona, move

**Screenshots**
![image](https://github.com/user-attachments/assets/a36f79c1-51ad-452b-906f-8e90a3921164)
![image](https://github.com/user-attachments/assets/ee3e0850-bea5-4513-ac99-4ab7edf2ca74)

**Additional context**

**Comment by Dueu** [comment]
Can confirm:
![wonkyspeed](https://github.com/user-attachments/assets/998b315f-19fd-4da5-84e0-5daa9406c6da)
I think the mime is a human, didnt take the exact number of the run but was today when I recorded it.

**Comment by MilonPL** [comment]
quick fix set the friction to 30 i have no idea what's writing over the speed modifier
