### ISSUE TITLE
Chicken stuck in carry position

### ISSUE THREAD

**Issue by Falinmog** [DeltaV-Station/Delta-v#2418]
## Description
Chicken stuck in carry position with hands free, can be removed by buckling the chicken onto a chair

**Reproduction**
Pull an object
carry a chicken
Drop the pulled item
Throw the chicken

**Screenshots**
![image](https://github.com/user-attachments/assets/d5784834-7944-4bec-89b9-860234f0d2f3)

**Additional context**
This does not work with large parcels from the mail room

**Comment by deltanedas** [comment]
was probably fixed i havent seen kiera kats with chicken army recently
