### ISSUE TITLE
Glimmer muted event doesnt work

### ISSUE THREAD

**Issue by DebugOk** [DeltaV-Station/Delta-v#245]
## Description
It discharges, but doesnt mute people

**Comment by PHCodes** [comment]
![image](https://github.com/DeltaV-Station/Delta-v/assets/47927305/b51a8cc3-526b-4a13-a6bd-d7f589dffbd5)

Having difficulty reproducing. You're running PsionicCatGotYourTongue, and not just on a bunch of Harpies, right?
(If you're not PotentialPsionic, you aren't added to the list of potential mute targets)

**Comment by DebugOk** [comment]
I'll have to check this again, but around the time this issue was made, the event did nothing on the server

**Comment by deltanedas** [comment]
event works

**Comment by DebugOk** [comment]
It was a bug relating to harpies not being psionic at the time
