### ISSUE TITLE
"Teach Person a Lesson" doesnt auto complete if target cryo's

### ISSUE THREAD

**Issue by Stop-Signs** [DeltaV-Station/Delta-v#2458]
## Description
greentext hunters in shambles when their easy kill objective enters le funny cryopod and they are doomed to the redtext of shame

**Reproduction**
roll antag
have teach a lesson objective
have your target go cryo
experience the redtext of shame
**Screenshots**

**Additional context**

**Comment by deltanedas** [comment]
you didnt teach john smith a lesson if you did nothing for 2 hours and only bought a gun when  evac came

**Comment by Lyndomen** [comment]
> you didnt teach john smith a lesson if you did nothing for 2 hours and only bought a gun when evac came

this is kinda my take too, sure it sucks that dude cyro'd the moment they didnt roll antag themself but shit happens.

**Comment by deltanedas** [comment]
yeah unlucky
