### ISSUE TITLE
verbs broken, again! (yes it happened again)

### ISSUE THREAD

**Issue by progamer12312369** [DeltaV-Station/Delta-v#2477]
Issue involving most admin right click options such as: Antag, Debug, Admin, Tricks, Smite.
All options other than debug > export sprite have vanished after merging latest delta v update into fork

**Reproduction**
Fork delta v, add custom music, merge latest updates, admin right click options vanish

**Screenshots**
![image](https://github.com/user-attachments/assets/3bcac19c-5d1e-4178-a42a-480bb8d2edc5)

**Additional context**
Delta-V forked server, fork is mainly just custom music.

**Comment by progamer12312369** [comment]
i think this might be a me issue hold on since my friend can do regular things like butcher with verbs

**Comment by deltanedas** [comment]
screenshot literally has Admin and Debug :trollface:

**Comment by progamer12312369** [comment]
aw shit the screenshot didnt do what i wanted, the only option in the menu is export sprite

**Comment by progamer12312369** [comment]
its too hard to screenshot in ss14 💔

**Comment by progamer12312369** [comment]
oh it was a client issue im so fuckjgoimn sorry
