### ISSUE TITLE
Lavaland storm doesn't work

### ISSUE THREAD

**Issue by fow111** [DeltaV-Station/Delta-v#2493]
## Description
Lavaland ashstorm doesn't deal any damage

**Reproduction**
Go to lavaland, wait for storm, go out

**Screenshots**
-

**Additional context**
-

**Comment by deltanedas** [comment]
it does, the start and end light storms dont

**Comment by deltanedas** [comment]
yeah it works, source: the new salv on shoko that almost got burned to death from being slow to get back to base

**Comment by deltanedas** [comment]
actually is real sometimes

**Comment by deltanedas** [comment]
so he just stepped in lava rip bozo
