### ISSUE TITLE
Zombie Outbreak Event does not get Syndicate Comms

### ISSUE THREAD

**Issue by Dirius77** [DeltaV-Station/Delta-v#2494]
## Description
When you acquire the initial infected status from a zombie outbreak event, you do not receive syndicate comms to allow communication with the other infected.

**Reproduction**
Enter a round, become infected through a zombie outbreak event instead of the regular roundstart initial infected.

**Screenshots**

**Additional context**
Round 18018 on Apoapsis had this occur.

**Comment by therealDLondon** [comment]
Intentional design

**Comment by deltanedas** [comment]
yep intentional, zombie outbreak is an outbreak not bioterrorism
