### ISSUE TITLE
Players can freely break cuffs in Zero-G

### ISSUE THREAD

**Issue by Cygnall** [DeltaV-Station/Delta-v#2515]
## Description
Players can break cuffs in zero-g with no way to stop them.

**Reproduction**
Gravity is off, anyone cuffed and held can break cuffs with no way to interrupt, including stun baton.

**Screenshots**
Sorry, don't have.

**Additional context**
This was really annoying. I even tried to seat them on something and unseat them. Nothing worked. Was trying to escort Perma to EVAC.

**Comment by Lyndomen** [comment]
out of curiosity, did you slap em?

**Comment by deltanedas** [comment]
you can just punch them yes
also upstream issue
