### ISSUE TITLE
Holopads need Delta V localisation changes and locations [Beginer Friendly]

### ISSUE THREAD

**Issue by IamVelcroboy** [DeltaV-Station/Delta-v#2531]
## Description
1. In locale, change "cargo" references to "logistics", "science" to "epistemics", "research director", "Quartermaster", etc.
2. Add DV specific holopads: 
- Justice (CJ, Clerk, Pros)
- Mailroom 
- Mantis
- Oracle
- Corpsman
- lavaland(long range?)

Upstream these probably
- cmd evac
- sec breakroom 
- Service room
- shooting range
- AME
- PA Control
- psych

**Reproduction**
n/a

**Comment by Avalon-Proto** [comment]
A few notes to this- holopads on shuttle should be Either Bluespace or quantum entangling, so that they function between maps. Long range pads only function in the same map but on different grids. Also I think a fun idea to add on would be to make a Syndicate version for the LP that can make calls but not be called. Whole providing the LP a set of chameleon clothing in order to utilize it

**Comment by IamVelcroboy** [comment]
> A few notes to this- holopads on shuttle should be Either Bluespace or quantum entangling, so that they function between maps. Long range pads only function in the same map but on different grids. Also I think a fun idea to add on would be to make a Syndicate version for the LP that can make calls but not be called. Whole providing the LP a set of chameleon clothing in order to utilize it

Will have to discuss how we want to do shuttles, because being off the map, they might just be "out of range" and that's ok.

**Comment by deltanedas** [comment]
long-range telepads work across grids on the same map which seem to do what you want

**Comment by Unkn0wnGh0st333** [comment]
Should have said I was working on this but I'm working on this

edit: The name changes and deltaV custom ones I mean

**Comment by deltanedas** [comment]
most of these are added now, not sure if lavaland should have one as you would be able to use it to call anyone i think

**Comment by Avalon-Proto** [comment]
> most of these are added now, not sure if lavaland should have one as you would be able to use it to call anyone i think

I would think a bluespace one at Lavaland would not be the worst thing to have. Let's the miners call ahead and tell medical they have someone who got scorched to death so they are ready to come pick em up

**Comment by deltanedas** [comment]
erm send a fax to medbay :nerd:

**Comment by IamVelcroboy** [comment]
Made upstream PR for the rest [#34110](https://github.com/space-wizards/space-station-14/pull/34110)
