### ISSUE TITLE
Carpeted table bug

### ISSUE THREAD

**Issue by SimpleGopnik** [DeltaV-Station/Delta-v#2549]
## Description
Carpeted tables when being constructed will consume the full stack of carpet in one's hand instead of just one, leading to all but one of the entire stack being deleted.

**Reproduction**
Go through the steps of making a table and add carpet to it with more than one item in the stack, when one goes back to crowbar the table and remove the carpet it will give you only one.

**Comment by deltanedas** [comment]
almost identical to medsec construction bug (needs changing from tags to a material that every carpet gets)

**Comment by IamVelcroboy** [comment]
Upstream has a fix [#33721](https://github.com/space-wizards/space-station-14/pull/33721)

**Comment by SimpleGopnik** [comment]
Ah splendid
