### ISSUE TITLE
Head roles can be revolutionaries.

### ISSUE THREAD

**Issue by Colin-Tel** [DeltaV-Station/Delta-v#260]
## Description

Of all the wacky things

**Reproduction**

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/113523727/dded442a-fd71-4549-89e6-8de993cbd2dc)

**Additional context**

**Comment by FluffiestFloof** [comment]
Working as intended according to the code :trollface:

**Comment by DebugOk** [comment]
Working as intended
