### ISSUE TITLE
Cyborgs can join with the nearsighted trait 

### ISSUE THREAD

**Issue by Colin-Tel** [DeltaV-Station/Delta-v#274]
## Description

They can't put on the glasses.

**Reproduction**

Select a character with the nearsighted trait
Join as cyborg

**Additional context**

Their vision is *not* augmented.

**Comment by DangerRevolution** [comment]
Not sure if it's worth opening a new issue since it stems to the same issue:
+ social anxiety is also carried over

This doesn't occur if you're gibbed and placed in an M-MI, only if you join with those traits selected.

**Comment by deltanedas** [comment]
i think theres already an issue upstream, about paracusia
