### ISSUE TITLE
Cameras on pebble dont seem to work

### ISSUE THREAD

**Issue by Adrian16199** [DeltaV-Station/Delta-v#278]
## Description

Tried to watch cameras, it just seems like none of em are working, could be also that there is no camera unit?

on another note, warden doesnt get his hardsuit

**Reproduction**

Try to watch cameras from the wireless camera monitor in security.

**Screenshots**

**Additional context**

**Comment by IamVelcroboy** [comment]
If this was mid-round, it's a longtime bug with camera networks. Not sure why, but sometimes they just drop their connection, maybe when power goes out 🤷‍♂️, and you can't reconnect.

**Comment by IamVelcroboy** [comment]
OK, confirmed this. It is on roundstart. I was able to fix by deleting/replacing the camera monitor in sec. (I didn't test any others)
