### ISSUE TITLE
Mystagogue doesn't have their Ifrit

### ISSUE THREAD

**Issue by FluffiestFloof** [DeltaV-Station/Delta-v#289]
## Description

Mystagogue doesn't get their Ifrit.
The main issue is that InnateTool doesn't work anymore (it doesn't give you the tools in your hand) and the Ifrit need a custom Body component to have two hands again.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Adrian16199** [comment]
Technicly speaking, resolved.

**Comment by deltanedas** [comment]
hijacking this issue, ifrit ghost role has Unknown as title and description and not ifrit

**Comment by Adrian16199** [comment]
> hijacking this issue, ifrit ghost role has Unknown as title and description and not ifrit

![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/575e92f3-14ea-40dd-ab0a-92177dd2ac83)
Odd, it looks fine when im checkin it in the dev.

**Comment by deltanedas** [comment]
so many live rounds i look in ghost roles and at the bottom

Unknown
-------------------
Unknown
Request | Follow

(when taken its just ifrit, possible one that another player /ghosted from?)

**Comment by Adrian16199** [comment]
Thats..... concerning. I will try to think of somethin.

**Comment by Guess-My-Name** [comment]
When someone ghosts from ifrit after it was initially taken, it changes to Unknown Unknown Unknown. Not sure if it always happens or just sometimes.
Pretty sure it's cause MobIfritFamiliar GhostRole component is missing those 3: name, description, rules.
