### ISSUE TITLE
List of base game things that should be disabled

### ISSUE THREAD

**Issue by DebugOk** [DeltaV-Station/Delta-v#3]
## Description
Placeholder

- [ ] Immovable rod event (cringe)

**Comment by DebugOk** [comment]
Test

**Comment by DebugOk** [comment]
Test

**Comment by Colin-Tel** [comment]
Clown Hardsuit *or* its improvements over the EVA suit.

**Comment by ps3moira** [comment]
deathmatch event (should be reserved for admin event or something but not a regular thing if pop reaches only 15 players)

**Comment by FluffiestFloof** [comment]
Moth able to eat more than just clothes.

**Comment by IamVelcroboy** [comment]
Asteroid rock changes. We have more/better options, including non-mineable ones and a very robust spawner 😉. I'll look at implementing this in a more friendly way when we get there or try to upstream it altogether.

**Comment by DebugOk** [comment]
> Moth not being able to eat more than just clothes.

> Clown Hardsuit or its improvements over the EVA suit.

Was this ever resolved?

**Comment by FluffiestFloof** [comment]
> > Moth not being able to eat more than just clothes.
> 
> > Clown Hardsuit or its improvements over the EVA suit.
> 
> Was this ever resolved?

#32 #170

**Comment by IamVelcroboy** [comment]
> Asteroid rock changes. We have more/better options, including non-mineable ones and a very robust spawner 😉. I'll look at implementing this in a more friendly way when we get there or try to upstream it altogether.

This was resolved a while ago.

**Comment by nok-ko** [comment]
Should this issue be closed at this point?
