### ISSUE TITLE
Mindbreaker needs to be added to the chem guidebook

### ISSUE THREAD

**Issue by DebugOk** [DeltaV-Station/Delta-v#306]
## Description
Along with any Delta drinks needing to be added to the bartending guidebook

**Comment by FluffiestFloof** [comment]
Both of them are automatically created, do they not look for custom drinks?

**Comment by FluffiestFloof** [comment]
![ss+(2023-10-25+at+04 56 43)](https://github.com/DeltaV-Station/Delta-v/assets/9823203/f77be8f9-070f-4c3e-9486-753b14a57c5f)
Our custom drinks are in but they need updated locale

**Comment by DebugOk** [comment]
> ![ss+(2023-10-25+at+04 56 43)](https://user-images.githubusercontent.com/9823203/278055054-f77be8f9-070f-4c3e-9486-753b14a57c5f.png) Our custom drinks are in but they need updated locale

They are automatically generated assuming the chem entry is added

**Comment by DebugOk** [comment]
Chems have to be added to [Resources/ServerInfo/Guidebook/Medical/Medicine.xml](https://github.com/DeltaV-Station/Delta-v/blob/master/Resources/ServerInfo/Guidebook/Medical/Medicine.xml)

**Comment by DebugOk** [comment]
(It only adds medicine, mindbreaker is tagged as toxin)

**Comment by FluffiestFloof** [comment]
Mindbreaker is in Chemicals
![ss+(2023-10-25+at+05 00 36)](https://github.com/DeltaV-Station/Delta-v/assets/9823203/cce6a85e-2c4f-4568-a6a1-2a0b204a57e6)
