### ISSUE TITLE
breaching hammer isn't usable as a crowbar

### ISSUE THREAD

**Issue by Carolyn3114** [DeltaV-Station/Delta-v#328]
## Description
you cannot breach with breaching hammer

**Reproduction**
try to pry open door
cry

**Screenshots**

**Additional context**

**Comment by Carolyn3114** [comment]
also, there is no cooldown for wielding/unwielding it

**Comment by Tryded** [comment]
> also, there is no cooldown for wielding/unwielding it

Think that's intended now, however I probably could make it act like a crowbar

**Comment by Carolyn3114** [comment]
> > also, there is no cooldown for wielding/unwielding it
> 
> Think that's intended now, however I probably could make it act like a crowbar

it's not intended, there is supposed to be a cooldown

**Comment by Adrian16199** [comment]
This issue should be closed.

**Comment by Colin-Tel** [comment]
bumping that this should be closed
