### ISSUE TITLE
Old Nyano/Delta shuttles should be ported over

### ISSUE THREAD

**Issue by DebugOk** [DeltaV-Station/Delta-v#346]
## Description
Low priority, but required for when shipyards get readded

**Comment by IamVelcroboy** [comment]
If I don't do this next week, remind me

**Comment by IamVelcroboy** [comment]
This might be finished. I'll double check next week.

**Comment by deltanedas** [comment]
i yoinked all the ships from pre rebase deltav not sure about nyano

**Comment by Axionyxx** [comment]
Assuming this is finished
