### ISSUE TITLE
Deathgasp causes absurd damage

### ISSUE THREAD

**Issue by VMSolidus** [DeltaV-Station/Delta-v#353]
## Description
Deathgasp gives whoever does it +200 aspyxiation damage, which makes people who don't know any better infuriating to revive because you now have to defib them 5 times. It really should just instantly set you to dead. This is infuriating for medbay players because people who don't know any better will use their last words to tell me how to do my job, and then make it harder to do my job. 

**Reproduction**
Go into crit, then use the deathgasp to say something, enjoy your free 200 asphyx

**Screenshots**
![image](https://github.com/DeltaV-Station/Delta-v/assets/16548818/be16abea-2f78-40da-9068-e953f70c8c76)
Pic related, someone who did this/

**Comment by Carolyn3114** [comment]
it could just give 100 asphyxiation

**Comment by DebugOk** [comment]
Then dont use deathgasp, taking damage for it inherited from ghosting, as the last words feature just forces you to /ghost.

```cs
            if (canReturnGlobal && TryComp(playerEntity, out MobStateComponent? mobState))
            {
                if (_mobState.IsCritical(playerEntity.Value, mobState))
                {
                    canReturn = true;

                    //todo: what if they dont breathe lol
                    //cry deeply
                    DamageSpecifier damage = new(_prototypeManager.Index<DamageTypePrototype>("Asphyxiation"), 200);
                    _damageable.TryChangeDamage(playerEntity, damage, true);
                }
            }
```
https://github.com/DeltaV-Station/Delta-v/blob/master/Content.Server/GameTicking/GameTicker.GamePreset.cs#L249-L260
