### ISSUE TITLE
Carrying somebody and placing them on a vehicle teleports them somewhere

### ISSUE THREAD

**Issue by FluffiestFloof** [DeltaV-Station/Delta-v#358]
## Description

**Reproduction**

- Carry someone
- Click drag their sprite into the wheelchair / ATV / possibly a chair
- They get teleported to a specific pos (possibly 0 0 0)
- Oh no

**Screenshots**

https://github.com/DeltaV-Station/Delta-v/assets/9823203/9f8e4959-3f2b-429d-9f67-a048d0f7e748

**Additional context**

**Comment by IamVelcroboy** [comment]
Vehicles kil
