### ISSUE TITLE
Hotplates not heating

### ISSUE THREAD

**Issue by FoxStellar** [DeltaV-Station/Delta-v#384]
## Description

So the hotplates in chemistry seem to be malfunctioning, they don't seem to heat at all.
Recipes that require heat in order to mix never actually mix because of this. There seems to be an indication of it not working -
that is as soon as you put the beaker on the hotplate, the red light flashes on and then off immediately, IIRC it's supposed to stay on to represent activity

**Reproduction**

Prepare a mixture in a beaker for something that needs heat like Sigynate 
Sodium Carbonate + Kelotane + Water + Sgr + Heat(370k) = 4 Sigynate 
place the beaker on the hotplate, witness the flashing, and let it sit for hours on end with no mixing

**Screenshots**

![SS14 Loader_yDnFDN7xVj](https://github.com/DeltaV-Station/Delta-v/assets/67992564/a773945d-cffe-491f-9be0-768c45945818)
This is me checking that I had the recipe correct in the beaker, I left the beaker sit for a long time and tried to place it several different times to get the light to stay on, but about 30 minutes later it still hadn't mixed

**Additional context**

I witnessed another chemist get the light to stay on on the hotplate, he said he pulled on the beaker ever so slightly, but even still
it didn't seem to mix after about 5 minutes

**Comment by deltanedas** [comment]
dupe

**Comment by FluffiestFloof** [comment]
Not a dupe here but upstream issue that is already reported on upstream https://github.com/space-wizards/space-station-14/issues/21274
You can temporarily counter that issue by dragging the beaker and just standing still.

**Comment by FluffiestFloof** [comment]
Fixed upsteam, so will be fixed here whenever we sync up to https://github.com/space-wizards/space-station-14/commit/77d49ea7e1ad016927229aefd15d7900da56a1c3

**Comment by luringens** [comment]
This works now.
