### ISSUE TITLE
Salvage debris maps ported from Nyano/Replace WD maps

### ISSUE THREAD

**Issue by IamVelcroboy** [DeltaV-Station/Delta-v#387]
I think @TadJohnson00 said they were doing this. If not, I will probably do it next week.

**Comment by TadJohnson00** [comment]
I was actually planning on replacing a lot of the current wrecks with brand new grids, including new salvage spawners and a tweak to the magnet to pull a majority of wrecks over asteroids. But, that being said, I have a few things on my plate right now so if it doesn't get done by next week, by all means port the debris grids from Nyano.

**Comment by IamVelcroboy** [comment]
@TadJohnson00, I ported Nyano maps and updated the Wizden ones. Feel free to keep working on the stuff you mentioned and if you want to still make any changes to salvage maps, go ahead. I'm closing this issue now though.
