### ISSUE TITLE
asterisk atmos has no axe

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#389]
## Description
title

**Reproduction**
1. ask ce for axe 3 times
2. dont get axe
3. atmos is 100C
4. spiders spawn and you cant defend yourself
5. almost die and go to med
6. get gibbed by a nazi on the way to med (real)

**Comment by deltanedas** [comment]
also atmos doesnt have atmos access (or i had extended access idk)

**Comment by Colin-Tel** [comment]
The only thing on Asterisk that requires Atmos access is the Atmos locker. Its Atmos is for all engineers.

**Comment by deltanedas** [comment]
ok but there is still no axe

**Comment by Colin-Tel** [comment]
Fair enough, now that I’m aware that it’s command and Atmos locked, I can move it out of CE’s little hidey hole
