### ISSUE TITLE
Felinids in duffelbags are immune to almost all damage

### ISSUE THREAD

**Issue by FluffiestFloof** [DeltaV-Station/Delta-v#394]
Mirrored from old Nyano issue since now it's our issue I suppose.
## Description

Currently Felinids hiding in a duffel bag has the following issues:
- They benefit from complete immunity against projectiles/lasers based guns while still able to shoot out of it. This can (and has been) be abused by people ~~to drain Nuclear Operatives Shuttle turrets of ammo.~~ It can also results in unfair firefights.
- They are also immune to melee attacks but you can just open the duffelbag and click them out.
- Explosions doesn't seem to affect Felinids that are inside the bag, wherever the source is from the outside or caused by the Felinid in said bag. This include the nuke explosion too.

**Reproduction**

Be a felinid, go in a duffel bag. Gain immunity against every damage but space air.

**Media**

<br>
Shooting

https://github.com/DeltaV-Station/Delta-v/assets/9823203/3e47d1df-34a7-485d-aeaa-49364c3bfaed

<br>
Outside explosion

https://github.com/DeltaV-Station/Delta-v/assets/9823203/48c5975e-432f-4fe9-a2bd-ad7e5f609a5d

<br>
Inside explosion

https://github.com/DeltaV-Station/Delta-v/assets/9823203/7b79167f-eba4-4706-a599-5f6f5579edf5

**Comment by luringens** [comment]
Just tried to reproduce this, and you now take explosion damage while in a duffelbag. This was likely fixed by https://github.com/space-wizards/space-station-14/pull/21625 .

**Comment by deltanedas** [comment]
issue still stands since projectiles still dont do damage

**Comment by Axionyxx** [comment]
This should be fixed? Will test and close if it is

**Comment by Axionyxx** [comment]
Melee and bullets don't damage bags, and as a result the felinid remains unharmed. But they can't shoot out, and explosions still hurt. I think this is fixed enough to be closed
