### ISSUE TITLE
Cannabis is no longer edible

### ISSUE THREAD

**Issue by FluffiestFloof** [DeltaV-Station/Delta-v#395]
## Description

Cannot eat cannabis leaves anymore. The menu button to eat them doesn't show up and can't do the alt click action to eat them automatically. 

It seems like no one can eat it, tested with felinids and humans at least.

**Reproduction**

Attempt to eat cannabis leaves (not dried).

**Screenshots**

N/A

**Additional context**

Phil gameplay is ruined by this, utmost urgency to fix.
In seriousness, potentially an issue from the diet thing.

**Comment by IamVelcroboy** [comment]
I looked into this, and imo, it's working as intended. Players should make edible items(brownies) if they want to eat weed.

Also, more edible options could be added.

**Comment by Carolyn3114** [comment]
you should be able to eat raw weed, but it shouldn't do anything

**Comment by IamVelcroboy** [comment]
Nah, basically the way it's set up is produce is split into 2 categories, raw ingredients/feedstock or readily edible.

The first is stuff like wheat, oats, etc. Creatures with 2 stomachs(cows, etc) can consume that category.

The second is stuff like apples, bananas, etc. Any creature can eat that.

**Comment by IamVelcroboy** [comment]
Long story short, you can still eat weed... If you're a cow 🐄

Bovine race when?

**Comment by leonardo-dabepis** [comment]
> Long story short, you can still eat weed... If you're a cow 🐄
> 
> Bovine race when?

so you're telling me i have to make Phil a cow?

**Comment by Adrian16199** [comment]
> > Long story short, you can still eat weed... If you're a cow 🐄
> > Bovine race when?
> 
> so you're telling me i have to make Phil a cow?

Someone needs to PR a cow morphotype now.

**Comment by IamVelcroboy** [comment]
> > Long story short, you can still eat weed... If you're a cow 🐄
> > Bovine race when?
> 
> so you're telling me i have to make Phil a cow?

Yep 😀

**Comment by IamVelcroboy** [comment]
Still don't think this is an issue.
