### ISSUE TITLE
Mind swap with a revolutionary allows you to see R icons

### ISSUE THREAD

**Issue by Guess-My-Name** [DeltaV-Station/Delta-v#396]
## Description
During a revolutionary round, when not a revolutionary yourself, after mind swapping with a revolutionary you get to see all the R icons, who is revolutionary, who is head revolutionary. Those icons disappear when you go back to your body.

**Reproduction**
Revolutionaries are around.
Don't be a revolutionary.
Have mind swap ability.
Mind swap with revolutionary/head revolutionary.

**Additional context**
Glitch encountered when swapping with a head rev, another rev was next to him, so i saw both blue and red R icon.
Possibly other way around is bugged too, meaning if you mind swap with someone who isn't a revolutionary as a revolutionary, you no longer see who is and isn't revolutionary during the mind swap.

**Comment by deltanedas** [comment]
should be done upstream, im guessing changing `HasComp<HeadRevolutionaryComponent>(uid)` to checking for rev role on mind would fix it, in client revolutionary system

**Comment by Axionyxx** [comment]
Is this still an issue? I'm too lazy to test it

**Comment by deltanedas** [comment]
we have revs disabled

**Comment by ghost** [comment]
Closing this as it's a non-issue for us essentially, unless you fork Delta and have revs enabled.
