### ISSUE TITLE
arena issues

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#423]
## Description
- fuel tank in engi is empty
- only 3 hardsuit lockers /!\

**Comment by IamVelcroboy** [comment]
Other than the fuel tank, there are only 3 engi slots. They don't need more and others can be found throughout the station. you removed the parallax issue as it was fixed.  So, I'm closing this. The fuel tank will be filled in a future update.

**Comment by deltanedas** [comment]
@IamVelcroboy also this disposal unit isnt piped
![19:08:36](https://github.com/DeltaV-Station/Delta-v/assets/39013340/96b39822-1720-4239-8c17-cc33ae31cac1)

also i dont know why every disposal unit has a tagger when a) there are no routers b) there is no tag set

**Comment by deltanedas** [comment]
and the fax in engineering is labelled cargo :trollface:

**Comment by IamVelcroboy** [comment]
> also i dont know why every disposal unit has a tagger when a) there are no routers b) there is no tag set

Because I always do that. I have my reasons :trollface:

**Comment by IamVelcroboy** [comment]
Good catch on the missing pipe and fax tag though. Will add to next update
