### ISSUE TITLE
corpsman salvage corpse has loot

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#428]
## Description
corpsman salvage corpse contain the following:
- full chest rig of meds
- rubber mk58
- knife in boots
- armour vest

the meds and pistol are very strong

**Comment by Carolyn3114** [comment]
every corpse has stuff like this

**Comment by deltanedas** [comment]
yeah but this is especially op

**Comment by DebugOk** [comment]
This should be removed
