### ISSUE TITLE
deep frying issues

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#439]
## Description
1. deep-fried-burnt-item isnt localized
2. if you deep fry a slicable food like pizza and slice it, the slices it makes are deep fried but the final slice made when used up is not

**Comment by luringens** [comment]
For number 1, this seems to be a typo, it should be `deep-fried-burned-item` which is localized. Fixing this would be a great first issue for a new contributor 🙂

**Comment by jzburda** [comment]
I gave it my best shot. If I understand the .ftl files and how they relate to the .cs files, that should fix part 1 of this issue

**Comment by Colin-Tel** [comment]
@deltanedas part one should be fixed with the above PR merged.

**Comment by deltanedas** [comment]
part 2 may already be fixed unless i hallucinated
