### ISSUE TITLE
telegnosis should make you ssd not catatonic

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#442]
## Description
catatonic can never return outside of trolling so it should say yellow text to avoid mixups with the biomass reclaimer

**Comment by VMSolidus** [comment]
I mean you shouldn't be using Telegnosis where people can find you. It's generally a good idea to hide somewhere when you want to use it. Dorms is a really good spot to do this, unless you're someone like command staff, but then you'd also have a convenient office to hide in. I also like to use lockers, and rooms rarely traveled in.

**Comment by deltanedas** [comment]
obviously if someone wants to murder you it wont help, but it would prevent innocent mistakes

**Comment by DebugOk** [comment]
You also shouldn't be grinding up people

**Comment by deltanedas** [comment]
if you see someones dead with purple text youd assume its free biomass not a dead telegnome

**Comment by DebugOk** [comment]
If you die in telegnosis you get severed and can't go back anyways
