### ISSUE TITLE
Bionic Syrinx doesn't imitate over the radio

### ISSUE THREAD

**Issue by VMSolidus** [DeltaV-Station/Delta-v#460]
## Description
Changing your name via the Bionic Syrinx only changes it when speaking in person. If you try to speak over the radio, even if your ID isn't on your person, then your voice will come out unmodified. 

**Reproduction**
-Be Harpy
-Put on a bionic syrinx
-Set your name to anything
-Try so speak on the radio

**Comment by luringens** [comment]
Yeah, it worked originally but I bet I broke it when I duplicated the code to deconflict with voice mask. IIRC it got the name from the voicemaskcomponent directly, so I'll have to touch upstream radio code to fix it so it also checks syrinxvoicemaskcomponent. Can probably look at it this weekend.
