### ISSUE TITLE
Nukie world doesn't have Pen and Paper

### ISSUE THREAD

**Issue by VMSolidus** [DeltaV-Station/Delta-v#466]
Yea so this isn't normally a problem, unless something really fucking weird happens, like oh I don't know, a Mute character somehow ends up as a Nukie for whatever strange reason. 
![image](https://github.com/DeltaV-Station/Delta-v/assets/16548818/1eaa16ca-44d8-4a27-9acb-734fa7a03c33)

In case it happens again, I'd like to request that the pool table in Nukie World come with pen and paper for the rare occasions where you get a mute nukie.

**Comment by DebugOk** [comment]
Nukies getting traits applied isn't intended as far as I know. We cannot modify the number map as it's a core file.
