### ISSUE TITLE
Player's movement impaired or disabled after being pushed into the wall via artifact.

### ISSUE THREAD

**Issue by RomanQrr** [DeltaV-Station/Delta-v#477]
## Description
After being pushed by an artifact into the wall, the player gets stuck and can't move. If another player pulls them out, the player's movement gets staggered like they are lagging, they start to move about half a second after the directional input. If player reloads the game while stuck, they can start to move normally, but get rubber banded back to the point they were stuck at. If at that point they interact with a chair, their position will be updated to be on the chair, but rubber banding will not go away. The problem resolves itself if player grabs the chair and tries to pull it with them, which returns their movement to normal.

**Reproduction**
Spawn an artifact with a depth 0 node that pushes you away once it triggers with a trigger of your choosing.
Position the artifact one tile away from the wall.
Step onto the tile between the wall and the artifact.
Trigger the artifact.
You should be stuck.

Another player pulling you out might cause stuttering in the step.
Reloading the game fixes the stutter step.

Changing positions (like sitting in a chair) won't enable movement back.

Reload the client. You should be able to move but be rubber banded back to the position you are stuck in.
Sit in a nearby chair. 
Unbuckle yourself from the chair. You should now be rubber banded to the position of the chair.
Pull the chair while you try to move away from it.
This should remove the rubber banding.

**Screenshots**
[Imgur](https://imgur.com/D2BN0gd)

**Additional context**
Found on Apoapsis, on November 25th at 10:00 AM GMT.

**Comment by UnicornOnLSD** [comment]
This does it too with the gravity anomaly's pulse, in game way to fix the impaired movement is going in a chute and out then, no issue.
