### ISSUE TITLE
Edge has wrongly placed wall chargers in security.

### ISSUE THREAD

**Issue by Adrian16199** [DeltaV-Station/Delta-v#490]
## Description

Wrongly placed charger.
**Reproduction**

>Go to security, 
>into the hallway, 
>try to use the charger
>The charger is facing towards inside of a wall
**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/9de55dbd-94f4-4c77-8588-2b4a847d1462)

**Additional context**

Pain

**Comment by Colin-Tel** [comment]
Wall chargers can’t be rotated and they suck

**Comment by Adrian16199** [comment]
It actualy works, for some reason however, it works on all sides of the wall so it can be accessed from HoS room and from the hall.
For some reason only a certain angle and the fact that I didnt had a laser equipped made it unable for me to examine it for some reason.
