### ISSUE TITLE
RevolutionaryRuleSystem's OnPostFlash should remove the command component if its present

### ISSUE THREAD

**Issue by DebugOk** [DeltaV-Station/Delta-v#509]
## Description
Like the title says. Right now it could cause issues with winning the round if you convert a deimplanted command member. This'll be resolved by what I'm working on, but I still wanted to make this issue.

**Comment by deltanedas** [comment]
new rev meta deimplant and flash every head real

**Comment by DebugOk** [comment]
> new rev meta deimplant and flash every head real

Exactly what we're going for
