### ISSUE TITLE
Tortuga's station disposal is not properly done.

### ISSUE THREAD

**Issue by Adrian16199** [DeltaV-Station/Delta-v#533]
## Description

3 conveyor belts (Picture showed in blue) are not powered (There is not enough LV cables in the room) and the recycler is putted the opposite way.
**Reproduction**

Go to disposals in tortuga
Try to use it.
Its not workin properly.
**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/fb23f7c2-768b-4c2c-b0a4-610b5f6cce73)

**Additional context**

Janitorial pain.

**Comment by IamVelcroboy** [comment]
So, this is working on my end. I might still flip the recycler but it works in both directions.

**Comment by Adrian16199** [comment]
Odd, literly most of the stuff didnt even wanted to get grinded when I tried it from that side, besides, it hurts my eyes seein that it is goin thro that side instead of thro the shredders.

**Comment by IamVelcroboy** [comment]
Right, I'll definitely flip it when I get a chance but the conveyors were working for me when I tested just a bit ago

**Comment by IamVelcroboy** [comment]
OK, I see what's happening. The corners are being powered by maints cables 
![image](https://github.com/DeltaV-Station/Delta-v/assets/107660393/e026ffc7-b8cf-463a-84de-f6b3c3722c00)

I'll put up a fix soon.

**Comment by IamVelcroboy** [comment]
This was fixed
