### ISSUE TITLE
Ectoplasm entity doesn't have ectoplasm reagent in it, normality crystals can't happen

### ISSUE THREAD

**Issue by Guess-My-Name** [DeltaV-Station/Delta-v#537]
## Description

Killed revenant spawns entity 'Ectoplasm' [(this)](https://github.com/DeltaV-Station/Delta-v/blob/master/Resources/Prototypes/Entities/Objects/Specific/Medical/morgue.yml#L127) that instead of ReagentId: Ectoplasm (instead of [this](https://github.com/DeltaV-Station/Delta-v/blob/master/Resources/Prototypes/Nyanotrasen/Reagents/psionic.yml#L97)) contains 5u of Ash and 5u of SpaceLube.

**Reproduction**

Kill a revenant, add dropped ectoplasm to a beaker, put it into a chemmaster, cry

**Screenshots**

**Additional context**

That's how it looked pre rebase [(click)](https://github.com/DeltaV-Station/Delta-v-Legacy/blob/master/Resources/Prototypes/Nyanotrasen/Entities/Objects/Specific/Chapel/ectoplasm.yml#L4)

**Comment by deltanedas** [comment]
upstream has an ectoplasm in same file as ash that has to be edited

**Comment by Guess-My-Name** [comment]
> upstream has an ectoplasm in same file as ash that has to be edited

yup, fix awaits in [this PR](https://github.com/DeltaV-Station/Delta-v/pull/538)
