### ISSUE TITLE
picking an item up causes crash-to-desktop

### ISSUE THREAD

**Issue by DangerRevolution** [DeltaV-Station/Delta-v#560]
## Description

Pulling an item, then picking it up crashes your client
**Reproduction**

1. Load the game
2. Enter server
3. Spawn Reptilian Player Character
4. Debug --> Control Mob
5. Walk up to the table, pull an item and then click it to pick it up
6. Have your game crash

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/04c498ff-22e9-4f75-b53c-16cc34356991)

**Additional context**

**Comment by deltanedas** [comment]
upstream issue and pvs thing doesnt matter

**Comment by DebugOk** [comment]
Upstream issue
