### ISSUE TITLE
Holiday PR Ideas Mega Issue

### ISSUE THREAD

**Issue by DEATHB4DEFEAT** [DeltaV-Station/Delta-v#561]
I feel like there's a better word than "Holiday" for this..

# Description

We need to keep a list of ideas we think of through out the year so we aren't like "What do we do?" when these events near.
Keep track of whoever suggested the idea and what the suggestion is.

## April Fools

- [ ] `Reece` - Add [DUBIDUBI](https://youtu.be/KlCjR8p2oko) as a lobby song
- [ ] `DEATHB4DEFEAT` - Make jobs infinite and/or add/remove random roles, pretty much a massive bureaucratic error sometimes occurring on round start
- [ ] `DEATHB4DEFEAT` - Wonkify maps (move departments around or make the stations look weird)
- [ ] `DEATHB4DEFEAT` - Just another tuesday - Give everyone a random antag with harmless objectives and 4TC or something
- [ ] `Dragnoir` - Make borgs see people wearing costumes as the mob that costume represents
- [ ] `Dragnoir` - Give random people clumsiness
- [ ] `Dragnoir` - Randomly swap walking on some people
- [ ] `Leonardo_DaBepis` - Add [Flötenkreis](https://youtu.be/BtW1xjNkFTo) as a lobby song

## Christmas

- [ ] `DEATHB4DEFEAT` - Christmas maps

## Halloween

- [ ] `DEATHB4DEFEAT` - Various costumes in the theater vendor or a new one placed around maps
- [ ] `DEATHB4DEFEAT` - Halloween maps
- [ ] `Dragnoir` - Make zombies more likely and give them funny looks
- [ ] `DEATHB4DEFEAT` - Ouija board, nearby ghosts get to fight over control and move the puck around to try to say *something*
- [ ] `Dragnoir` - Raging Revenants - Spawn a lot of revenants over time
- [ ] `Dragnoir` - Similar to the christmas tree, put a big pumpkin/group of pumpkins somewhere central that gives you a bucket full of random candy
- [ ] `Dragnoir` - Enable Skeletons roundstart
- [ ] `Dragnoir` - Add species-specific loadouts for Skeletons, a flaming horse, a motorcycle, and a cool cowboy/biker outfit
- [ ] `Ps3moira` - Make meteors giant pumpkins

## Valentines

- [ ] `DEATHB4DEFEAT` - If I make obsessed antag ever, randomly give a bunch of people obsession targets

**Comment by ps3moira** [comment]
Seasonal?

**Comment by ps3moira** [comment]
For Halloween, I was wanting to swap out meteors for giant pumpkins instead. As well as a lot of other Halloween content including a Halloween-themed vending machine that ended up not making it in time.

**Comment by deltanedas** [comment]
> Make borgs see people wearing costumes as the mob that costume represents

SPACE CARP YOU WILL CAUSE HARM!!!! PREPARE TO BE ELIMINATED

**Comment by DEATHB4DEFEAT** [comment]
> Seasonal?

April fools isn't a seasonal event

**Comment by deltanedas** [comment]
only occurs in spring im afraid, and thats a season

**Comment by DEATHB4DEFEAT** [comment]
> only occurs in spring im afraid, and thats a season

Everything is a seasonal event then.. hmm

**Comment by deltanedas** [comment]
Yes.
