### ISSUE TITLE
Vials can be inserted into the chemmaster, but dont appear anywhere in the UI

### ISSUE THREAD

**Issue by DebugOk** [DeltaV-Station/Delta-v#566]
## Description
Surely this can't be intended, right? Does it work on Wizden?

**Comment by FluffiestFloof** [comment]
Can be inserted in chemmaster/dispenser on Wizden, they also don't show up in the ui anywhere but take the same spot as the beaker.

**Comment by IamVelcroboy** [comment]
I reported upstream [#22861](https://github.com/space-wizards/space-station-14/issues/22861)

**Comment by Blazeror** [comment]
Fixed in space-wizards/space-station-14#23473

**Comment by Tonydatguy** [comment]
Shouldn't this be closed?
