### ISSUE TITLE
Default theme can have actions go off-screen for aghosts

### ISSUE THREAD

**Issue by DebugOk** [DeltaV-Station/Delta-v#567]
## Description
Maybe because I skipped a commit? I'm not sure, it doesnt happen on seperated though. The buttons from 1 to 0 appear fine, but anything after that can go off screen. (At least, on my crappy laptop)

**Comment by IamVelcroboy** [comment]
I made an issue for this upstream a couple weeks ago. Because it really messed up mapping actions
