### ISSUE TITLE
No tie, a disaster

### ISSUE THREAD

**Issue by UnicornOnLSD** [DeltaV-Station/Delta-v#599]
## Description
There are several ties in the game that are here for pure drip, however their only way of obtainability is through lucky maints looting, which, in itself is quite the issue as they are a MANDATORY asset for professional looks.
Maybe adding them as a drobe item would be nice, as the only one available so far is detective tie.

**Reproduction**
Find tie in maints, be happy.
Go look for tie on station another shift, no tie to be found anywhere.
Cry in lack of tie.

**Additional context**
Red ties are the best imo, but purple ones are cool too.

**Comment by ps3moira** [comment]
I think to not further bloat the clothing vend, making it printable at HoP would be fine. Give's them meaning in life at the very least.

**Comment by UnicornOnLSD** [comment]
Certainly, it was just a proposition, if we can get HoP to be a laundry manager by letting him print ties, hell, I'm all for it, I just want ties

**Comment by Adrian16199** [comment]
> I think to not further bloat the clothing vend, making it printable at HoP would be fine. Give's them meaning in life at the very least.

One would debate, should this be upstreamed, I could do it but im uncertain if upstream or not. I will probably upstream it and if they wont accept it, then I will simply do it in delta V.

**Comment by UnicornOnLSD** [comment]
true, didn't think of upstreaming it but fair, cheers adri
