### ISSUE TITLE
Crime assist bug

### ISSUE THREAD

**Issue by Adrian16199** [DeltaV-Station/Delta-v#614]
## Description

Crime assist seems to be missing Rsi.
**Reproduction**

>Crime assist.
>Answer following questions with the answers:
No, yes, yes ,yes.
It should then show the question being bugged.
**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/fe614ea9-28e8-40ee-b305-5509f22c3ad7)

**Additional context**

**Comment by deltanedas** [comment]
ftl* :trollface:

**Comment by Adrian16199** [comment]
Im going to *crime assist* you.

**Comment by Timfa2112** [comment]
Probably an easy fix, I'll get to it as soon as I can! Expecting it to be a typo in the key

**Comment by Timfa2112** [comment]
Fixed in https://github.com/DeltaV-Station/Delta-v/pull/619
