### ISSUE TITLE
Crime Assist Issues

### ISSUE THREAD

**Issue by Haltell** [DeltaV-Station/Delta-v#620]
## Description
1. Sexual Harassment doesn't display correctly.
2. Perjury or False Report doesn't display correctly.
3. When the question "Was the suspect selling or distributing the illicit items?" Crime Assist does not advance.
**Reproduction**

In Crime Assist:
1. Start > No > No > No > No > No > No > Yes
2. Start > No > No > No > No > No > No > No > Yes > Yes
3. Start > No > No > No > Yes > No > Yes

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/15059141/38fe236f-f87b-4d85-a66b-238db446eb8f)
![image](https://github.com/DeltaV-Station/Delta-v/assets/15059141/8b352fc4-967b-424e-a537-3b3f5546e37a)

**Additional context**

The first two are probably just improperly defined FTLs, third may be an issue with the program itself.

**Comment by Timfa2112** [comment]
The ftl issues should be resolved, and the third was likely a yaml typo.
They _should_ be fixed already, can you confirm if it's still an issue?

**Comment by DebugOk** [comment]
These should all be fixed
