### ISSUE TITLE
Zombies can speak coherently in Telepathic chat

### ISSUE THREAD

**Issue by Timfa2112** [DeltaV-Station/Delta-v#641]
## Description
Zombies keep their psionics, which means they keep access to Telepathic chat and are able to speak in it coherently

**Reproduction**
Be psionic, get bitten by a zombie

**Additional context**
Forum post in Discord: https://discord.com/channels/968983104247185448/1191905721839792198/1191905721839792198
Related issue (zombies keeping psionics): https://discord.com/channels/968983104247185448/1191833877954691082/1191833877954691082

**Comment by Arkormuffin** [comment]
I can comfirme this issue and the Reproduction is acurrect.

**Comment by Gyrandola** [comment]
I think this should be closed.
[#679 ](https://github.com/DeltaV-Station/Delta-v/pull/679)
