### ISSUE TITLE
Syndicate Reinforcement Monkey not keeping up with normal monkey

### ISSUE THREAD

**Issue by Guess-My-Name** [DeltaV-Station/Delta-v#642]
## Description

Syndie Reinforcement monkeys need a hand to pull objects, they also can't strip people.
Normal monkeys that become sentient can pull with their tail (just like reptilians) and can strip people.

**Reproduction**

Become syndicate reinforcement monkey
Take something into your hand
Try to pull, can't

Become syndicate reinforcement monkey
Open a strip menu of someone else
Try to take things off of them, can't

**Screenshots**

**Additional context**

[MobMonkeySyndicateAgent parent is SimpleMobBase](https://github.com/DeltaV-Station/Delta-v/blob/master/Resources/Prototypes/Entities/Mobs/NPCs/animals.yml#L1698), so any features that are added to a normal monkey need to be added separately to reinforcement monkey in yaml as well. Didn't check if it's the same on upstream or not, if it is - it should probably be reported and fixed there.

**Comment by deltanedas** [comment]
its upstream issue

syndie monkey and normal monkey should share a parent then monkey adds its unique component

**Comment by Axionyxx** [comment]
This seems to have been resolved in https://github.com/space-wizards/space-station-14/pull/23642
