### ISSUE TITLE
Psionic invisiblity makes you completely invisible to everyone.

### ISSUE THREAD

**Issue by Adrian16199** [DeltaV-Station/Delta-v#647]
## Description

You cant find the person as a ghost, borg or even animals.
**Reproduction**

>Get psionic invisibility
>Use it
>Become invisible even to ghosts unless they use ghostwarp on said person but it renders the person constantly naked to them.

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/79e6f555-15b1-41be-ac26-4cf0efd3e971)
![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/18ff41c5-6b16-4f24-9e96-06563c8a8fa6)
![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/e3b64fd7-0d20-4889-accb-d6b9c780f8f4)

**Additional context**

And yes, I china laked the room to find the invisible guy because I lost him.

**Comment by Adrian16199** [comment]
I forgot to change the name before postin as i was testin somethin. :elp:

**Comment by UnicornOnLSD** [comment]
The power in itself may be bugged completely as I have also seen moments where I could see someone who was invisible by wearing psi insulation and then still able to see them once I wasn't insulated anymore.

**Comment by Guess-My-Name** [comment]
> The power in itself may be bugged completely as I have also seen moments where I could see someone who was invisible by wearing psi insulation and then still able to see them once I wasn't insulated anymore.

that is a different bug, related to psionic insulation, basically once you wear insulation once, you are insulated forever and see all telegnosis and invisible people for the rest of the round
