### ISSUE TITLE
Edge Issues

### ISSUE THREAD

**Issue by IamVelcroboy** [DeltaV-Station/Delta-v#652]
## Description
Several things have been reported about Edge. Putting them here so they are all in one place.

- Warden missing hardsuit
- Blast doors in captains room don't have a switch
- Medical missing cameras
- No Navmap beacons on warp points(can hold off on this until next upstream merge. They changed them.)

**Comment by DangerRevolution** [comment]
![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/eed83527-461c-4f02-95e6-d9354109972f)

disposals in security is broken
