### ISSUE TITLE
shoko needs oxy miner yoinked

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#664]
## Description
notafet ops is gone we can recycle co2 again

**Comment by Adrian16199** [comment]
Check again

![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/5ea987be-81c8-4883-9dac-8246a593fa89)

(I didnt put it back when the christmas version was reverted)

**Comment by Adrian16199** [comment]
I felt too lazy to put it there again.

**Comment by deltanedas** [comment]
o i thought it was kept :trollface:
