### ISSUE TITLE
Digging got broken by the latest merge

### ISSUE THREAD

**Issue by DebugOk** [DeltaV-Station/Delta-v#727]
## Description
Shoko looking a little silly nowadays

Will probably require https://github.com/DeltaV-Station/Delta-v/pull/400 to be reverted and redone entirely to work with the new systems.

**Screenshots**
![image](https://github.com/DeltaV-Station/Delta-v/assets/49997488/3c76390a-118d-4be6-88da-a5b81676580f)

**Comment by IamVelcroboy** [comment]
Might as well address [this](https://github.com/DeltaV-Station/Delta-v/issues/663) at the same time.

**Comment by IamVelcroboy** [comment]
Related upstream [PR](https://github.com/space-wizards/space-station-14/pull/24432/files#diff-31fe8c976548b5947468eb9d2553c3306a20139d714a96a21fa1c706f4219ccd)

**Comment by IamVelcroboy** [comment]
I also wonder if this was ever attempted to be upstreamed? And if it should be? To avoid future regressions maybe...
