### ISSUE TITLE
Camera adjustments required for Arena

### ISSUE THREAD

**Issue by UnicornOnLSD** [DeltaV-Station/Delta-v#755]
## Description
Arena's cams has salvage bay on the engineering router rather than supply.

**Reproduction**
Get telescreen, cam router or whatever, select Engineering cameras, salvage bay be there

**Screenshots**
![image](https://github.com/DeltaV-Station/Delta-v/assets/149102472/0c0a8346-63a4-4138-ad84-4f317930ee92)

**Additional context**
wawa

**Comment by deltanedas** [comment]
also the disposal unit in atmos just stops at atmos :trollface:

**Comment by IamVelcroboy** [comment]
Rebase'll getcha. I'll look into these soon.
