### ISSUE TITLE
edge issues

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#764]
## Description
gas miners have grilles over the walls bruh
![05:12:27](https://github.com/DeltaV-Station/Delta-v/assets/39013340/535ce83c-fee8-4ebc-aeea-c0dd8e54e324)

now that chems are limited no reason to not give chem some dispensers, they are below poverty right now

**Comment by AitorLogedo** [comment]
grilles are intended to be there im pretty sure

**Comment by deltanedas** [comment]
its really wierd looks like it used to all be windows and they got replaced

**Comment by Colin-Tel** [comment]
Working on this right now.
