### ISSUE TITLE
submarine issues

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#771]
## Description
- **med is run off 1 apc** it fucks power so much
- the teg and burn chamber are total dogwater i will personally redo them after next update
- theres a plasma miner too op, also theres no plasma cans
- some scrubbers are connected to distro __/!\\__

**Comment by UnicornOnLSD** [comment]
1. Medical has two APCs, West and East Hospital
2. Didn't to TEG setup, last patch included more radiators for the sake of it
3. Plasma miner is getting removed in next patch
4. do point out which scrubbers, I can't change something I don't know of

**Comment by deltanedas** [comment]
a single 55kw apc powers the entire medbay it needs more (ramping cant cope and it makes power flicker a lot i believe)

the radiators are bad but i dont care, the teg piping and "burn chamber" are the jokes

and i have nfi which scrubbers are evil use toolshed to find scrubbers with pipecolor that isnt waste idk

**Comment by UnicornOnLSD** [comment]
APC will get fixed next patch

You got the chamber

I'm alright with changing scrubbers but if you can't show them to me I can't really see, I'll take a look but if I don't see'em I don't see'em

**Comment by deltanedas** [comment]
`> entities with Scrubber ?????basically whatever to Comp<AtmosPipeColor>() and make sure its waste??? pos`

**Comment by UnicornOnLSD** [comment]
Alright, all should be cool, scrubber was found, it was, in fact, singular thanks for reporting it

**Comment by deltanedas** [comment]
at least its not multiple of them :trollface:
