### ISSUE TITLE
Opened mail too big for trash bag

### ISSUE THREAD

**Issue by UnicornOnLSD** [DeltaV-Station/Delta-v#796]
## Description
Opened mail too big for trash bag

**Reproduction**
get mail, open mail, get trash bag, put mail in trash bag, can't because too big
RIP cuz'o gridinv

**Screenshots**
N/A
**Additional context**
I can't clean trash that doesn't fit the holy bag

**Comment by Adrian16199** [comment]
![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/3dda2c3d-dffd-4d1a-8ca2-73eb14dc2ddf)
![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/ced58d7b-9190-49d2-98ed-44ad10ee0201)

It looks fine to me.
