### ISSUE TITLE
replays crash the launcher

### ISSUE THREAD

**Issue by JoeHammad1844** [DeltaV-Station/Delta-v#810]
## Description

cant maej bideo of epik trolg

**Comment by DebugOk** [comment]
Cant do anything without logs

**Comment by JoeHammad1844** [comment]
round 9720

**Comment by DebugOk** [comment]
I'm looking into this now, but if its not caused by the replays being messed up theres nothing I can do about it

**Comment by DebugOk** [comment]
It doesn't crash for me with that exact replay

**Comment by JoeHammad1844** [comment]
odd

**Comment by JoeHammad1844** [comment]
maybe im doing something wrong? i just drag the zip onto the launcher, right?

**Comment by JoeHammad1844** [comment]
i got it working, i just downloaded it again
