### ISSUE TITLE
microwave can roll DV-SpareSafe

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#828]
## Description
its not *terrible* since if you are in the vault with agent id, id card boxes and microwave rolling for it you can just
a. if you are traitor/thief just emag the cabinet
b. copy every access including cap then you dont need the safe at all

but idk

**Comment by DebugOk** [comment]
Has this actually happened in round? Seems like a very minor thing since non-antags doing it is bwoinkable and antags can just emag it anyways.

You'd need insane luck anyways, it seems like a lot of effort for something that you can solve in many other ways

**Comment by deltanedas** [comment]
i have only done it in sandbox with 2 boxes of id cards, have never seen it live

**Comment by Axionyxx** [comment]
This would likely require altering a ton of systems to make sure the access is actually completely unobtainable, I'm not sure if thats worth it

**Comment by MilonPL** [comment]
Not an issue, after discussing it with the direction team.

**Comment by deltanedas** [comment]
free AA maker is real
