### ISSUE TITLE
Asterisk is missing captain's drobe

### ISSUE THREAD

**Issue by Adrian16199** [DeltaV-Station/Delta-v#836]
## Description

The drobe that have clothing for the heads is missing in captain's quarters.
**Reproduction**

Play map
Be captain
No drip.
**Screenshots**

**Additional context**

**Comment by noctyrnal** [comment]
Asterisk is missing all of the command drobes I believe, or atleast Captain's and CE's.

**Comment by Colin-Tel** [comment]
It’s tough fitting in so much stuff in the command rooms; I’ll see what I can do.
