### ISSUE TITLE
Paradox Anomaly doesn't spawn

### ISSUE THREAD

**Issue by DangerRevolution** [DeltaV-Station/Delta-v#868]
## Description

Paradox Anom reintroduced in #825 doesn't spawn :(, running the "addgamerule" command doesn't work for it.

I suspect it's because "MidRoundAntagRule" component, where Paradox Anom is set to spawn under, isn't uncommented out in midround.yml in the Delta folder.
**Reproduction**

forcemap Pebble
restartroundnow
addgamerule ParadoxAnomaly
aghost
no paradox anomaly

**Additional context**

As above, Paradox Anomalies were stuck into "MidRoundAntagRule" and that isn't uncommented out since rebase :O

This barely explains why RatKing spawns, as it's only otherwise included as a rare spawn in the "mouse migration event" which just spawns mice off the grid and makes them die ( a seperate upstream issue) but still. Refer to #rebase and #contributors on discord too o7

**Comment by DangerRevolution** [comment]
As a little +1 I'm pretty sure that Rat Kings don't spawn either; only spawning through a 0.05 variant of the "mouse migration" event. Might be worth looking into that :O

**Comment by deltanedas** [comment]
yeah paradox anomaly rule is for the anomaly itself not spawning i forgor that the midround rule was commented out :trollface:
