### ISSUE TITLE
Carrying somebody and meatspiking glitches out UI

### ISSUE THREAD

**Issue by FluffiestFloof** [DeltaV-Station/Delta-v#875]
## Description

If you are carrying a body and click drag their sprite to the meatspike, after the doafter you will receive two free `VIRTUAL ITEMS YOU SHOULD NOT SEE THIS` and a bunch of clientside errors.

**Reproduction**

- Kill poor Urist McHands
- Pick up dead Urist McHands
- Click drag their sprite unto the meat spike
- Wait for doafter
- UI gets glitched out, even the console doesn't appear and your hands holds two virtual items

**Screenshots**
![ss (2024-02-20 at 08 40 57)](https://github.com/DeltaV-Station/Delta-v/assets/9823203/d1167821-f1fc-4540-b0aa-b59e4cb2dca9)
This is pretty much all you can see on the UI

**Additional context**

Not the most game breaking bug since you can 'drop' both of those items to get back your hands, UI and ability to do everything.

**Comment by DebugOk** [comment]
Should be easy enough to fix, theres events that exist

**Comment by Axionyxx** [comment]
Not present anymore in current master
