### ISSUE TITLE
Feature Request: Mantis Maintenance Airlock

### ISSUE THREAD

**Issue by DangerRevolution** [DeltaV-Station/Delta-v#891]
## Description

There's no maints airlock for the mantis, which would be useful for mapping, espc to make the Psionic Knife a little more antag accessible.

**Comment by rosieposieeee** [comment]
while messing with airlocks, it would also be nice to have corpsman airlocks, since they lack them & anyone can walk into their room

may try and do both of these myself

**Comment by IamVelcroboy** [comment]
Mail and LO(upstream) need maint airlocks as well
