### ISSUE TITLE
MidRoundAntagRule is in desperate need of a rewrite

### ISSUE THREAD

**Issue by DebugOk** [DeltaV-Station/Delta-v#899]
## Description
Right now it can allow rat kings or paradox anomalies to spawn on unintended grids like Central Command or salvage grids. This should be an easy fix by copying what VentCrittersRule does

**Comment by DebugOk** [comment]
GlimmerMobRule has the exact same flaw, which can then cascade into also allowing revenants to spawn at central

**Comment by DebugOk** [comment]
I might revert the pr that enabled it until this can be fixed

**Comment by deltanedas** [comment]
theres thing for getting event capable station other rules use sobit should be fairly simple
