### ISSUE TITLE
event antag slime has antag rules but smile description

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#908]
## Description
![00:13:00](https://github.com/DeltaV-Station/Delta-v/assets/39013340/3137d91c-1efc-4ab4-a77e-f12a03621f88)

\>You are friendly to others
\>You are allowed to attack the crew without provocation

**Comment by ghost** [comment]
Simple 5 minute sidequest for a new contributor, if this hasn't been fixed already by us or upstream (which I'd close this issue if it was):
- Find ghost role descriptions YAML / Locale file
Could go one of two ways.
FTL: (calling locale strings = loc-strings here, fyi)
- Find description for normal hostile slimes, something like "Everything around you irritates your senses." 
- Change the loc-string for Smile's description to the long version of that. 
YAML:
- Find where it refers to the ghost role description for hostile slimes. See if it points to the smile loc-string
- Change it to point to the hostile slime loc-string
