### ISSUE TITLE
Reverse engineering machine has room for improvement

### ISSUE THREAD

**Issue by UnicornOnLSD** [DeltaV-Station/Delta-v#916]
## Description
The reverse engineering machine exists, and no longers has ways to "upgrade" it's speed.
It also lacks an heat producing counterpart/upgrade, unlike the Ore processor, proto and autolathe.
It doesn't get as much uses but having an upgrade would overall just be nice 👍

TL:DR, upgrade for the RE machine similar to the others ?

**Reproduction**
Look at RE machine
Slow
No way to make it faster

**Comment by DangerRevolution** [comment]
RE machine probably needs more functionality and more *things* to RE + Nanotrasen counterparts made before bothering to make a more efficient version of it or whatnot

**Comment by DangerRevolution** [comment]
Might be worth thinking one day if it's worth just upstreaming the RE machine? Given our distaste for Combat, we won't have much use out of Syndies & Syndie weapons but Wizden would have something to do with it + could make things to be RE-ed?? Unless at some point somewhere Wizden staff said they aren't interested?

**Comment by UnicornOnLSD** [comment]
Maybe, all I know is that currently it's very outclassed and the little use it has is unpractical

**Comment by Squishy77** [comment]
I'm attempting to work on it, alongside the things around it, I'm goanna start adding the new items from the rebase research tree and likely remove the handheld objective because it's kind of goofy that you can re a syndicate handheld into a regular one to complete it.

**Comment by UnicornOnLSD** [comment]
Something about the RE machine is in the works, yeepee.
