### ISSUE TITLE
paradox doesnt copy accent

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#921]
## Description
dont know why but had someone with a scottish accent get paradox anom and the clone had no accent

**Comment by DebugOk** [comment]
`PlayerSpawnCompleteEvent` uses the profile of the player being loaded, and I dont think its even called for paradox anomalies. You'd need to manually add all the components probably

**Comment by Axionyxx** [comment]
This is probably fixed
