### ISSUE TITLE
Pebble warp points are mis-named or duplicates or missing mega-thread

### ISSUE THREAD

**Issue by DangerRevolution** [DeltaV-Station/Delta-v#940]
## Description

It's called "Bombing Target" from the "Bombing Target" warp point not being named.

**Reproduction**

1. Load into game
2. Open Pebble
3. Open WarpPoints

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/0289f501-09ca-4589-9b27-0fb54374d933)

**Additional context**

Solutions:
1. Name the "Warp Point" component on the bombing target entity to uh, the actual warp point
2. Attach the "Bombing Target" component to any of the station beacons instead, which just takes the name from the "Warp Point" component and adds it to the Ninja's Bombing Targets

**Comment by DangerRevolution** [comment]
In a similar vein:

![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/3e6ceff1-3a2f-4a16-aac8-3f37739ba530)
![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/fff55d56-d99d-4bb1-af1a-bba6a401cc0e)
![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/32fb0eb9-d4f0-46b4-a55e-dbcbd27a28b3)
![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/c6d3a332-758a-4322-8c9c-d959f9915d4c)
![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/219cf2a0-10f2-404d-9e17-df89f2c6d2b0)
![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/81f1505a-9b16-43b5-8f08-f7560e84aa5a)
![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/7f7dc597-ad13-45ec-8aaa-6ee02ef12701)
![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/a1444587-ac92-47f4-b0d2-0b15e960a776)



Probably should be called "Head of Security" and "Head of Personnel", we infrequently get new players to Delta and having acronyms in important places like Warp Points isn't ideal.
"Warden's Office" or "Warden's Quarters" would also be better but that's just me being pedantic.

Again, "Grav" is somewhat okay, someone can shift click to figure out what they're looking at but it should *still* be called Gravity Generator. (although that's me also being pedantic)

Again, Detective should probably be called "Detective's Office" or "Detective's Quarter" but that's more pedantry.

Again, anyone can figure out that they're looking at Chemistry but for the "vibes" and for the fact that we're *assuming* someone can figure out it's Chemistry.

CMO and CE: refer to above point about HoS and HoP.

Atmos, Anom, Artifact (ignore Armory) all should probably have longer names explaining what they are. Again, this is for "Vibes" and for actual overall appearance. This thread quickly ballooned as I scrolled through the warp-list.

You can guess what I'm going to say about the Janitor's office.

**Comment by DangerRevolution** [comment]
![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/2aa6f933-2d55-4f0b-a21e-e8ebc58ee562)

Security also has two beacons.

**Comment by DangerRevolution** [comment]
![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/7945b1bc-851a-49e5-9022-4224df6390ba)

Engineering also has two beacons.

**Comment by DangerRevolution** [comment]
![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/3c7b239f-2ec1-438b-96af-5e0d61267b2b)

There are two bridge warp points.

**Comment by DangerRevolution** [comment]
![image](https://github.com/DeltaV-Station/Delta-v/assets/142105406/8e2090d0-b311-485e-a5c1-cef7e5b26e03)

Chapel is a duplicate warp
Cryosleep probably wasn't renamed off of it's original Locale string, hence it's right at the bottom and it also isn't capitalised so doesn't fit in with the rest of the map.

That's all folks :)

**Comment by deltanedas** [comment]
> Attach the "Bombing Target" component to any of the station beacons instead, which just takes the name from the "Warp Point" component and adds it to the Ninja's Bombing Targets

if you do this players can reposition bombing targets to wherever they like which is bad

**Comment by DangerRevolution** [comment]
> > Attach the "Bombing Target" component to any of the station beacons instead, which just takes the name from the "Warp Point" component and adds it to the Ninja's Bombing Targets
> 
> if you do this players can reposition bombing targets to wherever they like which is bad

Does it not stick to the warp point, which is set to not follow the beacon? Or do warp points follow Beacons?

Does Ninja have a pin pointer for their bombing point??

**Comment by deltanedas** [comment]
> Does it not stick to the warp point, which is set to not follow the beacon? Or do warp points follow Beacons?

beacons are warp points

**Comment by DangerRevolution** [comment]
> > Does it not stick to the warp point, which is set to not follow the beacon? Or do warp points follow Beacons?
> 
> beacons are warp points

Warp points follow beacons? 😢  that's so dumb

**Comment by IamVelcroboy** [comment]
Yeah, you can attach the bombing target to a standard warp point but not a beacon. Beacons can be moved. And yes, this is silly.

Alternatively, you can remove the warp point from a ninja target so it doesn't show in the list.

**Comment by DangerRevolution** [comment]
I assumed that the "Bombing Target" that appears for the Ninja took the name off the warp point? I'm assuming that means it's just better to make the bombing targets Points of Interest that aren't Interesting enough to be put on the NavMap.

**Comment by UnicornOnLSD** [comment]
Hello, hi, yes, this issue was seen, heard and will be addressed in a soon:tm: PR
