### ISSUE TITLE
Sec Hud/Glasses glitching and becoming nonfunctional.

### ISSUE THREAD

**Issue by rosieposieeee** [DeltaV-Station/Delta-v#966]
## Description

I figure this is probably some kind of layering issue because it happens when you move around and fixes/breaks in consistent areas, though those areas change over time. Happens with medsec too. Oddly, doesn't happen with the regular med hud bars. Don't know if it happens upstream, I don't play any other servers.

Really annoying because it makes a key sec tool basically worthless half the time for reasons out of your control.

**Reproduction**

Put 'em on and walk around.

**Screenshots**

From the discord thread:
![image](https://github.com/DeltaV-Station/Delta-v/assets/52761126/57cbf265-8425-4a9a-9104-5fa5a14cab13)

**Comment by Gyrandola** [comment]
pretty sure this is an upstream issue

**Comment by Adrian16199** [comment]
> pretty sure this is an upstream issue

It was not actualy!

**Comment by rosieposieeee** [comment]
going to close assuming this was fixed with #1052
