### ISSUE TITLE
Drinks from the Nyano/DV base need to be moved to the new metamorphic glasses

### ISSUE THREAD

**Issue by IamVelcroboy** [DeltaV-Station/Delta-v#985]
## Description
One of the last merges added glasses that revert to an empty glass when empty which applies specifically to pre-mapped drinks which didn't metamorph before.

**Comment by FluffiestFloof** [comment]
~~This change requires a lot of new sprites.~~
Nah actually it doesn't I just didn't approach the thing correctly. I'll still make some new sprites otherwise they won't look empty and it'll be sad.
