### ISSUE TITLE
Map Render Bot is broken

### ISSUE THREAD

**Issue by IamVelcroboy** [DeltaV-Station/Delta-v#986]
## Description
The PR bot that pulls map files, renders them, and pushes to the website has stopped working a while ago. Debug set this up. So, I'm unsure if anyone other than Debug knows how to fix it but we should look into it. Otherwise, we'll need to go back to updating the wiki manually again.

**Comment by Axionyxx** [comment]
From the looks of it, its doing something

**Comment by IamVelcroboy** [comment]
See also, the map display page linked in the wiki, has been broken for a little while too.

**Comment by Axionyxx** [comment]
> See also, the map display page linked in the wiki, has been broken for a little while too.

Which relies on SS14.Mapserver, yes. One issue fixed would also mean the other is fixed

**Comment by Axionyxx** [comment]
Its almost done with rerendering every map, and is now also tiled. So the webpage will load a lot better
